-- Smart CMU Maintenance: one-shot Supabase setup (schema + storage bucket + demo data).
-- Paste into Supabase → SQL Editor → Run. Safe to re-run: it clears existing app data first.
-- Generated by scripts/export-setup-sql.ts — do not edit by hand.
-- All tables are created in schema "SmartCMU" (identifier is case-sensitive).

create schema if not exists "SmartCMU";
set search_path to "SmartCMU", public, extensions;

-- ===== 001_init.sql =====
-- Smart CMU Maintenance Request System — initial schema
-- Works on Supabase Postgres and on plain Postgres 15+ (and PGlite for local dev).

-- gen_random_uuid() is built into Postgres 13+, no extension needed.

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('reporter', 'technician', 'admin')),
  full_name text not null default '',
  user_type text check (user_type in ('student', 'staff')),
  faculty text,
  phone text,
  profile_completed boolean not null default false,
  pdpa_accepted_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id serial primary key,
  name_th text not null,
  icon text not null default 'Wrench',
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table if not exists technician_skills (
  technician_id uuid not null references users(id) on delete cascade,
  category_id int not null references categories(id) on delete cascade,
  primary key (technician_id, category_id)
);

create table if not exists campuses (
  id serial primary key,
  name_th text not null
);

create table if not exists buildings (
  id serial primary key,
  campus_id int not null references campuses(id) on delete cascade,
  name_th text not null
);

create table if not exists rooms (
  id serial primary key,
  building_id int not null references buildings(id) on delete cascade,
  floor int not null,
  name_th text not null
);

create table if not exists request_code_counters (
  yymm text primary key,
  last_value int not null
);

create table if not exists requests (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  reporter_id uuid not null references users(id),
  category_id int not null references categories(id),
  room_id int not null references rooms(id),
  landmark text,
  description text not null,
  urgency text not null default 'normal' check (urgency in ('low', 'normal', 'urgent')),
  status text not null default 'pending' check (status in (
    'pending', 'accepted', 'assigned', 'in_progress', 'waiting_parts', 'need_info',
    'completed', 'closed', 'cancelled', 'rejected', 'reopened'
  )),
  status_before_info text,
  assigned_technician_id uuid references users(id),
  merged_into_id uuid references requests(id),
  reject_reason text,
  reopen_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  closed_at timestamptz
);

create index if not exists requests_reporter_idx on requests(reporter_id);
create index if not exists requests_technician_idx on requests(assigned_technician_id);
create index if not exists requests_status_idx on requests(status);
create index if not exists requests_room_category_idx on requests(room_id, category_id);
create index if not exists requests_created_idx on requests(created_at);

create table if not exists request_images (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  url text not null,
  kind text not null check (kind in ('before', 'after')),
  created_at timestamptz not null default now()
);

create table if not exists request_followers (
  request_id uuid not null references requests(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, user_id)
);

create table if not exists status_history (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_id uuid references users(id),
  note text,
  created_at timestamptz not null default now()
);
create index if not exists status_history_request_idx on status_history(request_id, created_at);

create table if not exists repair_notes (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  cause text not null,
  parts_used text,
  technician_id uuid references users(id),
  created_at timestamptz not null default now()
);

create table if not exists info_requests (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  asked_by uuid references users(id),
  question text not null,
  answer text,
  answered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists ratings (
  request_id uuid primary key references requests(id) on delete cascade,
  score int not null check (score between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  request_id uuid references requests(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on notifications(user_id, created_at desc);

-- The app talks to Postgres from the server only (service connection).
-- Lock the tables away from Supabase's public anon/authenticated API roles.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'alter table users enable row level security';
    execute 'alter table categories enable row level security';
    execute 'alter table technician_skills enable row level security';
    execute 'alter table campuses enable row level security';
    execute 'alter table buildings enable row level security';
    execute 'alter table rooms enable row level security';
    execute 'alter table request_code_counters enable row level security';
    execute 'alter table requests enable row level security';
    execute 'alter table request_images enable row level security';
    execute 'alter table request_followers enable row level security';
    execute 'alter table status_history enable row level security';
    execute 'alter table repair_notes enable row level security';
    execute 'alter table info_requests enable row level security';
    execute 'alter table ratings enable row level security';
    execute 'alter table notifications enable row level security';
  end if;
end $$;

-- ===== 002_supabase_storage.sql =====
-- Supabase only: public bucket for request photos (skipped on plain Postgres / PGlite).
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'storage' and table_name = 'buckets') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('request-images', 'request-images', true, 1258291, array['image/jpeg', 'image/png'])
    on conflict (id) do nothing;
  end if;
end $$;

-- ===== demo data =====
truncate users, categories, technician_skills, campuses, buildings, rooms, request_code_counters, requests, request_images, request_followers, status_history, repair_notes, info_requests, ratings, notifications restart identity cascade;

insert into users (id, username, password_hash, role, full_name, user_type, faculty, phone, profile_completed, pdpa_accepted_at, is_active, created_at) values
  ('d0293d6e-854e-48b6-8cc0-b695e41ed64e', 'student01', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', '', null, null, null, false, null, true, now() - interval '3 seconds'),
  ('6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 'staff01', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'ศิริพร คำแสน', 'staff', 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี (CAMT)', '0812345601', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('84ecc920-c6f8-40e5-8923-be0daffbc0c0', 'tech01', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'technician', 'สมศักดิ์ ใจดี', null, null, '0891112201', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('03139b66-4845-46eb-96ba-0a737abc8095', 'tech02', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'technician', 'วิชัย ศรีสุข', null, null, '0891112202', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('0c36e328-4637-433d-a9c7-2480e1448e42', 'tech03', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'technician', 'ธนากร แก้วมณี', null, null, '0891112203', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('d840e44a-ed29-4fd1-b5d1-9bc826243b96', 'admin01', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'admin', 'พรทิพย์ วงศ์ใหญ่', null, null, '053941000', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 'student02', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'ณัฐวุฒิ ปัญญาดี', 'student', 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี (CAMT)', '0812345610', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('117fb892-4d82-4137-ba29-69aa2028da00', 'student03', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'กมลชนก อินทร์แก้ว', 'student', 'คณะวิศวกรรมศาสตร์', '0812345611', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('631af0fb-1c6b-4a4e-adf2-d70792cd19cc', 'student04', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'ภูริภัทร สายสุวรรณ', 'student', 'คณะบริหารธุรกิจ', '0812345612', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 'student05', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'พิมพ์ชนก ทองดี', 'student', 'คณะแพทยศาสตร์', '0812345613', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('ed42646d-e662-45ad-9029-03ede427fdbe', 'student06', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'ธนภัทร มณีวงศ์', 'student', 'คณะพยาบาลศาสตร์', '0812345614', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('91f675d6-2bf8-4078-834a-fc905fab4da2', 'staff02', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'อรุณี บุญมา', 'staff', 'สำนักหอสมุด', '0812345615', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds'),
  ('05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 'staff03', '$2b$10$WCjDPfIctiHmqjWUUvDyoOrRIh7gB99MI9bJWtAV52Wv6ncuHOr/m', 'reporter', 'ประเสริฐ ชัยวงค์', 'staff', 'กองกิจการนักศึกษา', '0812345616', true, now() - interval '7776003 seconds', true, now() - interval '3 seconds');

insert into categories (id, name_th, icon, is_active, sort_order) values
  (1, 'ไฟฟ้า', 'Zap', true, 0),
  (2, 'ประปา', 'Droplets', true, 1),
  (3, 'เครื่องปรับอากาศ', 'AirVent', true, 2),
  (4, 'อุปกรณ์ IT', 'Monitor', true, 3),
  (5, 'เฟอร์นิเจอร์', 'Armchair', true, 4),
  (6, 'อาคารและสถานที่', 'Building2', true, 5),
  (7, 'อื่น ๆ', 'Ellipsis', true, 6);

insert into technician_skills (technician_id, category_id) values
  ('84ecc920-c6f8-40e5-8923-be0daffbc0c0', 1),
  ('84ecc920-c6f8-40e5-8923-be0daffbc0c0', 3),
  ('03139b66-4845-46eb-96ba-0a737abc8095', 2),
  ('03139b66-4845-46eb-96ba-0a737abc8095', 6),
  ('03139b66-4845-46eb-96ba-0a737abc8095', 5),
  ('0c36e328-4637-433d-a9c7-2480e1448e42', 4),
  ('0c36e328-4637-433d-a9c7-2480e1448e42', 7),
  ('0c36e328-4637-433d-a9c7-2480e1448e42', 1);

insert into campuses (id, name_th) values
  (1, 'วิทยาเขตสวนสัก'),
  (2, 'วิทยาเขตสวนดอก'),
  (3, 'วิทยาเขตแม่เหียะ');

insert into buildings (id, campus_id, name_th) values
  (1, 1, 'อาคาร CAMT'),
  (2, 1, 'อาคารเรียนรวม'),
  (3, 1, 'สำนักหอสมุด'),
  (4, 1, 'หอพักนักศึกษา 5'),
  (5, 1, 'อาคารคณะวิศวกรรมศาสตร์ 30 ปี'),
  (6, 2, 'อาคารเรียนรวม คณะแพทยศาสตร์'),
  (7, 2, 'อาคารคณะพยาบาลศาสตร์'),
  (8, 2, 'หอพักนักศึกษาแพทย์'),
  (9, 3, 'อาคารศูนย์ประชุม'),
  (10, 3, 'อาคารปฏิบัติการวิจัย');

insert into rooms (id, building_id, floor, name_th) values
  (1, 1, 1, 'ห้อง 101'),
  (2, 1, 1, 'ห้อง 102'),
  (3, 1, 1, 'ห้อง 103'),
  (4, 1, 1, 'ห้อง 104'),
  (5, 1, 2, 'ห้อง 201'),
  (6, 1, 2, 'ห้อง 202'),
  (7, 1, 2, 'ห้อง 203'),
  (8, 1, 2, 'ห้อง 204'),
  (9, 1, 3, 'ห้อง 301'),
  (10, 1, 3, 'ห้อง 302'),
  (11, 1, 3, 'ห้อง 303'),
  (12, 1, 3, 'ห้อง 304'),
  (13, 1, 4, 'ห้อง 401'),
  (14, 1, 4, 'ห้อง 402'),
  (15, 1, 4, 'ห้อง 403'),
  (16, 1, 4, 'ห้อง 404'),
  (17, 1, 5, 'ห้อง 501'),
  (18, 1, 5, 'ห้อง 502'),
  (19, 1, 5, 'ห้อง 503'),
  (20, 1, 5, 'ห้อง 504'),
  (21, 2, 1, 'ห้อง 101'),
  (22, 2, 1, 'ห้อง 102'),
  (23, 2, 1, 'ห้อง 103'),
  (24, 2, 1, 'ห้อง 104'),
  (25, 2, 1, 'ห้อง 105'),
  (26, 2, 2, 'ห้อง 201'),
  (27, 2, 2, 'ห้อง 202'),
  (28, 2, 2, 'ห้อง 203'),
  (29, 2, 2, 'ห้อง 204'),
  (30, 2, 2, 'ห้อง 205'),
  (31, 2, 3, 'ห้อง 301'),
  (32, 2, 3, 'ห้อง 302'),
  (33, 2, 3, 'ห้อง 303'),
  (34, 2, 3, 'ห้อง 304'),
  (35, 2, 3, 'ห้อง 305'),
  (36, 2, 4, 'ห้อง 401'),
  (37, 2, 4, 'ห้อง 402'),
  (38, 2, 4, 'ห้อง 403'),
  (39, 2, 4, 'ห้อง 404'),
  (40, 2, 4, 'ห้อง 405'),
  (41, 3, 1, 'ห้อง 101'),
  (42, 3, 1, 'ห้อง 102'),
  (43, 3, 1, 'ห้อง 103'),
  (44, 3, 2, 'ห้อง 201'),
  (45, 3, 2, 'ห้อง 202'),
  (46, 3, 2, 'ห้อง 203'),
  (47, 3, 3, 'ห้อง 301'),
  (48, 3, 3, 'ห้อง 302'),
  (49, 3, 3, 'ห้อง 303'),
  (50, 4, 1, 'ห้อง 101'),
  (51, 4, 1, 'ห้อง 102'),
  (52, 4, 1, 'ห้อง 103'),
  (53, 4, 1, 'ห้อง 104'),
  (54, 4, 2, 'ห้อง 201'),
  (55, 4, 2, 'ห้อง 202'),
  (56, 4, 2, 'ห้อง 203'),
  (57, 4, 2, 'ห้อง 204'),
  (58, 4, 3, 'ห้อง 301'),
  (59, 4, 3, 'ห้อง 302'),
  (60, 4, 3, 'ห้อง 303'),
  (61, 4, 3, 'ห้อง 304'),
  (62, 4, 4, 'ห้อง 401'),
  (63, 4, 4, 'ห้อง 402'),
  (64, 4, 4, 'ห้อง 403'),
  (65, 4, 4, 'ห้อง 404'),
  (66, 5, 1, 'ห้อง 101'),
  (67, 5, 1, 'ห้อง 102'),
  (68, 5, 1, 'ห้อง 103'),
  (69, 5, 1, 'ห้อง 104'),
  (70, 5, 2, 'ห้อง 201'),
  (71, 5, 2, 'ห้อง 202'),
  (72, 5, 2, 'ห้อง 203'),
  (73, 5, 2, 'ห้อง 204'),
  (74, 5, 3, 'ห้อง 301'),
  (75, 5, 3, 'ห้อง 302'),
  (76, 5, 3, 'ห้อง 303'),
  (77, 5, 3, 'ห้อง 304'),
  (78, 5, 4, 'ห้อง 401'),
  (79, 5, 4, 'ห้อง 402'),
  (80, 5, 4, 'ห้อง 403'),
  (81, 5, 4, 'ห้อง 404'),
  (82, 6, 1, 'ห้อง 101'),
  (83, 6, 1, 'ห้อง 102'),
  (84, 6, 1, 'ห้อง 103'),
  (85, 6, 1, 'ห้อง 104'),
  (86, 6, 2, 'ห้อง 201'),
  (87, 6, 2, 'ห้อง 202'),
  (88, 6, 2, 'ห้อง 203'),
  (89, 6, 2, 'ห้อง 204'),
  (90, 6, 3, 'ห้อง 301'),
  (91, 6, 3, 'ห้อง 302'),
  (92, 6, 3, 'ห้อง 303'),
  (93, 6, 3, 'ห้อง 304'),
  (94, 6, 4, 'ห้อง 401'),
  (95, 6, 4, 'ห้อง 402'),
  (96, 6, 4, 'ห้อง 403'),
  (97, 6, 4, 'ห้อง 404'),
  (98, 7, 1, 'ห้อง 101'),
  (99, 7, 1, 'ห้อง 102'),
  (100, 7, 1, 'ห้อง 103'),
  (101, 7, 1, 'ห้อง 104'),
  (102, 7, 2, 'ห้อง 201'),
  (103, 7, 2, 'ห้อง 202'),
  (104, 7, 2, 'ห้อง 203'),
  (105, 7, 2, 'ห้อง 204'),
  (106, 7, 3, 'ห้อง 301'),
  (107, 7, 3, 'ห้อง 302'),
  (108, 7, 3, 'ห้อง 303'),
  (109, 7, 3, 'ห้อง 304'),
  (110, 8, 1, 'ห้อง 101'),
  (111, 8, 1, 'ห้อง 102'),
  (112, 8, 1, 'ห้อง 103'),
  (113, 8, 2, 'ห้อง 201'),
  (114, 8, 2, 'ห้อง 202'),
  (115, 8, 2, 'ห้อง 203'),
  (116, 8, 3, 'ห้อง 301'),
  (117, 8, 3, 'ห้อง 302'),
  (118, 8, 3, 'ห้อง 303'),
  (119, 8, 4, 'ห้อง 401'),
  (120, 8, 4, 'ห้อง 402'),
  (121, 8, 4, 'ห้อง 403'),
  (122, 9, 1, 'ห้อง 101'),
  (123, 9, 1, 'ห้อง 102'),
  (124, 9, 1, 'ห้อง 103'),
  (125, 9, 2, 'ห้อง 201'),
  (126, 9, 2, 'ห้อง 202'),
  (127, 9, 2, 'ห้อง 203'),
  (128, 10, 1, 'ห้อง 101'),
  (129, 10, 1, 'ห้อง 102'),
  (130, 10, 1, 'ห้อง 103'),
  (131, 10, 2, 'ห้อง 201'),
  (132, 10, 2, 'ห้อง 202'),
  (133, 10, 2, 'ห้อง 203'),
  (134, 10, 3, 'ห้อง 301'),
  (135, 10, 3, 'ห้อง 302'),
  (136, 10, 3, 'ห้อง 303');

insert into request_code_counters (yymm, last_value) values
  ('2607', 8),
  ('2608', 18),
  ('2609', 15);

insert into requests (id, code, reporter_id, category_id, room_id, landmark, description, urgency, status, status_before_info, assigned_technician_id, merged_into_id, reject_reason, reopen_count, created_at, updated_at, completed_at, closed_at) values
  ('c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'MR-2607-0001', '91f675d6-2bf8-4078-834a-fc905fab4da2', 2, 33, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '5090942 seconds', now() - interval '4695150 seconds', now() - interval '4803038 seconds', now() - interval '4695150 seconds'),
  ('2a4e8f8b-6380-4835-965f-747935369775', 'MR-2607-0002', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 5, 88, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'low', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4998490 seconds', now() - interval '4826030 seconds', now() - interval '4928956 seconds', now() - interval '4826030 seconds'),
  ('67a0fd20-d3f6-4c82-81d1-6106deb88775', 'MR-2607-0003', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 1, 47, 'โต๊ะแถวสุดท้ายฝั่งหน้าต่าง', 'ปลั๊กไฟใต้โต๊ะแถวหลังไม่มีไฟ เสียบชาร์จโน้ตบุ๊กไม่ได้', 'normal', 'closed', null, '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, null, 0, now() - interval '4837343 seconds', now() - interval '4647887 seconds', now() - interval '4754902 seconds', now() - interval '4647887 seconds'),
  ('b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'MR-2607-0004', 'ed42646d-e662-45ad-9029-03ede427fdbe', 4, 2, null, 'ไมโครโฟนไร้สายมีเสียงซ่า ใช้สอนไม่ได้', 'urgent', 'closed', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '4710293 seconds', now() - interval '4554788 seconds', now() - interval '4690470 seconds', now() - interval '4554788 seconds'),
  ('1080d44d-426e-4799-918b-77623d48d614', 'MR-2607-0005', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 6, 56, 'มุมห้องด้านหลัง', 'ฝ้าเพดานมีรอยน้ำซึมและเริ่มโป่ง กลัวจะหล่นลงมา', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4573622 seconds', now() - interval '4366117 seconds', now() - interval '4445936 seconds', now() - interval '4366117 seconds'),
  ('32914f53-981b-4c2b-964e-0bcceabfd971', 'MR-2607-0006', '117fb892-4d82-4137-ba29-69aa2028da00', 6, 54, 'หน้าบันไดหนีไฟ', 'กระเบื้องพื้นทางเดินแตกและยกตัว เดินสะดุดง่าย', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4485627 seconds', now() - interval '4229860 seconds', now() - interval '4319507 seconds', now() - interval '4229860 seconds'),
  ('2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'MR-2607-0007', '91f675d6-2bf8-4078-834a-fc905fab4da2', 5, 62, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'low', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4309962 seconds', now() - interval '4142115 seconds', now() - interval '4266396 seconds', now() - interval '4142115 seconds'),
  ('f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'MR-2607-0008', '117fb892-4d82-4137-ba29-69aa2028da00', 2, 78, 'ห้องน้ำชาย ห้องสุดท้าย', 'ชักโครกกดน้ำไม่ลง น้ำไหลค้างในถัง', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4245545 seconds', now() - interval '4077909 seconds', now() - interval '4082349 seconds', now() - interval '4077909 seconds'),
  ('714752fc-e0e5-4edc-bf2e-98797b32f802', 'MR-2608-0001', '117fb892-4d82-4137-ba29-69aa2028da00', 6, 35, null, 'ผนังมีรอยร้าวยาวตั้งแต่ขอบหน้าต่างลงมา', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '4114395 seconds', now() - interval '3899483 seconds', now() - interval '3945131 seconds', now() - interval '3899483 seconds'),
  ('0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'MR-2608-0002', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 6, 13, 'หน้าบันไดหนีไฟ', 'กระเบื้องพื้นทางเดินแตกและยกตัว เดินสะดุดง่าย', 'urgent', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3986396 seconds', now() - interval '3718202 seconds', now() - interval '3777741 seconds', now() - interval '3718202 seconds'),
  ('af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'MR-2608-0003', 'ed42646d-e662-45ad-9029-03ede427fdbe', 5, 17, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3822288 seconds', now() - interval '3506993 seconds', now() - interval '3677587 seconds', now() - interval '3506993 seconds'),
  ('f130ec87-da99-4cb1-bb7c-77a338cf480c', 'MR-2608-0004', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', 6, 75, 'ประตูหลัง', 'ประตูห้องปิดไม่ได้ ลูกบิดชำรุด', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3691501 seconds', now() - interval '3413829 seconds', now() - interval '3552741 seconds', now() - interval '3413829 seconds'),
  ('7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'MR-2608-0005', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 1, 35, 'โต๊ะแถวสุดท้ายฝั่งหน้าต่าง', 'ปลั๊กไฟใต้โต๊ะแถวหลังไม่มีไฟ เสียบชาร์จโน้ตบุ๊กไม่ได้', 'normal', 'closed', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '3551910 seconds', now() - interval '3392993 seconds', now() - interval '3403824 seconds', now() - interval '3392993 seconds'),
  ('1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'MR-2608-0006', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 5, 62, 'ตู้หลังห้อง', 'ประตูตู้เก็บของหลุดจากบานพับ', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3429282 seconds', now() - interval '3313020 seconds', now() - interval '3341732 seconds', now() - interval '3313020 seconds'),
  ('308979ed-8ee6-4813-9a32-b4ca5d44182e', 'MR-2608-0007', '117fb892-4d82-4137-ba29-69aa2028da00', 5, 125, null, 'โต๊ะเรียนขาโยก เขียนหนังสือลำบาก', 'urgent', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3334306 seconds', now() - interval '3087095 seconds', now() - interval '3233812 seconds', now() - interval '3087095 seconds'),
  ('6dcaab19-e84f-433c-a32c-e2f947049974', 'MR-2608-0008', 'ed42646d-e662-45ad-9029-03ede427fdbe', 4, 16, 'แถวที่ 3 เครื่องที่ 12', 'คอมพิวเตอร์เครื่องที่ 12 เปิดไม่ติด ไฟไม่เข้า', 'urgent', 'closed', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '3223665 seconds', now() - interval '2920638 seconds', now() - interval '3129664 seconds', now() - interval '2920638 seconds'),
  ('55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'MR-2608-0009', 'ed42646d-e662-45ad-9029-03ede427fdbe', 2, 21, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '3074791 seconds', now() - interval '2870749 seconds', now() - interval '2972644 seconds', now() - interval '2870749 seconds'),
  ('1bb75d56-e04f-4c9c-8215-b7a9cfd0910d', 'MR-2608-0010', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 1, 1, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'normal', 'cancelled', null, null, null, null, 0, now() - interval '2954989 seconds', now() - interval '2952982 seconds', null, null),
  ('dc0fb709-d61f-4c59-9e39-2aef773ad342', 'MR-2608-0011', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 1, 131, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'urgent', 'rejected', null, null, null, 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', 0, now() - interval '2812682 seconds', now() - interval '2804577 seconds', null, null),
  ('c6121b35-e511-4d2d-af53-4f528f015e65', 'MR-2608-0012', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 3, 1, 'เครื่องฝั่งหน้าต่าง', 'แอร์เปิดแล้วไม่เย็น มีแต่ลมออก นักศึกษานั่งเรียนร้อนมาก', 'normal', 'closed', null, '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, null, 0, now() - interval '2706357 seconds', now() - interval '2407669 seconds', now() - interval '2591030 seconds', now() - interval '2407669 seconds'),
  ('30320fa7-8e59-4e4f-b866-347eb7bca1df', 'MR-2608-0013', '117fb892-4d82-4137-ba29-69aa2028da00', 2, 108, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'normal', 'closed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '2564532 seconds', now() - interval '2277540 seconds', now() - interval '2438138 seconds', now() - interval '2277540 seconds'),
  ('7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'MR-2609-0001', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 7, 25, null, 'ป้ายบอกทางหนีไฟหลุดออกจากผนัง', 'normal', 'completed', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '104597 seconds', now() - interval '16062 seconds', now() - interval '16062 seconds', null),
  ('1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'MR-2609-0002', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 6, 55, 'ประตูหลัง', 'ประตูห้องปิดไม่ได้ ลูกบิดชำรุด', 'normal', 'completed', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '85656 seconds', now() - interval '9568 seconds', now() - interval '9568 seconds', null),
  ('e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'MR-2609-0003', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', 1, 28, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'normal', 'completed', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '129986 seconds', now() - interval '66747 seconds', now() - interval '66747 seconds', null),
  ('adf498a9-3ed0-4542-bcf3-4844bf374f2d', 'MR-2608-0014', '117fb892-4d82-4137-ba29-69aa2028da00', 4, 38, null, 'ไมโครโฟนไร้สายมีเสียงซ่า ใช้สอนไม่ได้', 'normal', 'waiting_parts', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '2085223 seconds', now() - interval '2048533 seconds', null, null),
  ('d84b516b-2ed1-41b9-9f57-b93d3f0d0c24', 'MR-2608-0015', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 3, 1, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'urgent', 'waiting_parts', null, '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, null, 0, now() - interval '1923904 seconds', now() - interval '1875365 seconds', null, null),
  ('3222fcab-a078-490d-9b5d-fb56b4c4ae8a', 'MR-2608-0016', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 4, 45, null, 'Wi-Fi @JumboPlus หลุดบ่อยในห้องนี้ เชื่อมต่อไม่ได้เกือบทั้งห้อง', 'normal', 'in_progress', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '1839332 seconds', now() - interval '1790944 seconds', null, null),
  ('a4d34295-bac0-43fd-9579-57a2604d08f9', 'MR-2608-0017', 'ed42646d-e662-45ad-9029-03ede427fdbe', 3, 87, null, 'รีโมตแอร์หาย และตั้งอุณหภูมิที่ตัวเครื่องไม่ได้', 'normal', 'in_progress', null, '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, null, 0, now() - interval '1699223 seconds', now() - interval '1599313 seconds', null, null),
  ('e76a2af6-7bec-4969-b651-014d525a36ec', 'MR-2608-0018', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 5, 118, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'urgent', 'in_progress', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '1547607 seconds', now() - interval '1532939 seconds', null, null),
  ('1856829a-26d2-4f94-b4e4-bb3f2c7ac617', 'MR-2609-0004', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 1, 2, 'ทางเดินหน้าลิฟต์', 'ไฟทางเดินกะพริบตลอดเวลา ตอนกลางคืนมองไม่ค่อยเห็น', 'normal', 'assigned', null, '0c36e328-4637-433d-a9c7-2480e1448e42', null, null, 0, now() - interval '1393797 seconds', now() - interval '1368304 seconds', null, null),
  ('9f40f755-7765-4de0-9693-ca81fb8aa66f', 'MR-2609-0005', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 3, 12, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'normal', 'assigned', null, '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, null, 0, now() - interval '1312506 seconds', now() - interval '1284623 seconds', null, null),
  ('e211a617-8f14-487b-b814-9c341539ba4f', 'MR-2609-0006', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 2, 27, 'ห้องน้ำชาย ห้องสุดท้าย', 'ชักโครกกดน้ำไม่ลง น้ำไหลค้างในถัง', 'normal', 'assigned', null, '03139b66-4845-46eb-96ba-0a737abc8095', null, null, 0, now() - interval '1189680 seconds', now() - interval '1171885 seconds', null, null),
  ('03161cad-9353-4c6d-ab23-02491153962e', 'MR-2609-0007', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 3, 35, null, 'รีโมตแอร์หาย และตั้งอุณหภูมิที่ตัวเครื่องไม่ได้', 'normal', 'accepted', null, null, null, null, 0, now() - interval '1031952 seconds', now() - interval '1030749 seconds', null, null),
  ('20df381a-5640-4861-ab71-889f1544fa22', 'MR-2609-0008', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 2, 79, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'urgent', 'accepted', null, null, null, null, 0, now() - interval '898864 seconds', now() - interval '895566 seconds', null, null),
  ('c7e2610f-7b0e-43e7-8696-5f3833641844', 'MR-2609-0009', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 2, 105, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'low', 'need_info', 'pending', null, null, null, 0, now() - interval '810538 seconds', now() - interval '808078 seconds', null, null),
  ('8f8009e8-5f11-4195-923c-df6f4794478e', 'MR-2609-0010', '117fb892-4d82-4137-ba29-69aa2028da00', 3, 30, 'เหนือโต๊ะแถวที่ 3', 'แอร์มีน้ำหยดลงบนโต๊ะเรียน ต้องย้ายที่นั่ง', 'normal', 'cancelled', null, null, null, null, 0, now() - interval '699542 seconds', now() - interval '695847 seconds', null, null),
  ('90c384c1-de9c-460f-840e-801f1a06c0b7', 'MR-2609-0011', '117fb892-4d82-4137-ba29-69aa2028da00', 1, 105, 'ทางเดินหน้าลิฟต์', 'ไฟทางเดินกะพริบตลอดเวลา ตอนกลางคืนมองไม่ค่อยเห็น', 'normal', 'rejected', null, null, null, 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', 0, now() - interval '542832 seconds', now() - interval '521703 seconds', null, null),
  ('5d8ce707-d593-4dd1-82c2-d8c595cca332', 'MR-2609-0012', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', 3, 78, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'normal', 'pending', null, null, null, null, 0, now() - interval '424186 seconds', now() - interval '424186 seconds', null, null),
  ('5f3c685b-e8be-4f28-999b-af4e7f307e91', 'MR-2609-0013', '117fb892-4d82-4137-ba29-69aa2028da00', 6, 27, 'มุมห้องด้านหลัง', 'ฝ้าเพดานมีรอยน้ำซึมและเริ่มโป่ง กลัวจะหล่นลงมา', 'low', 'pending', null, null, null, null, 0, now() - interval '262660 seconds', now() - interval '262660 seconds', null, null),
  ('b40ff856-0e5d-4fe2-9924-1d5452bd495b', 'MR-2609-0014', '91f675d6-2bf8-4078-834a-fc905fab4da2', 7, 99, 'หน้าทางเข้าหลัก', 'มีรังผึ้งขนาดใหญ่ใต้ชายคาหน้าอาคาร นักศึกษาเดินผ่านบ่อย', 'normal', 'pending', null, null, null, null, 0, now() - interval '141211 seconds', now() - interval '141211 seconds', null, null),
  ('45055c37-c213-4542-990c-03effd668e0e', 'MR-2609-0015', 'ed42646d-e662-45ad-9029-03ede427fdbe', 2, 51, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'normal', 'pending', null, null, null, null, 0, now() - interval '42222 seconds', now() - interval '42222 seconds', null, null);

insert into request_images (id, request_id, url, kind, created_at) values
  ('7e192ee3-fc99-4876-9652-e265dad86d29', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', '/seed/pipe-before.jpg', 'before', now() - interval '5090942 seconds'),
  ('36fee125-5eab-4a93-91a7-194a5b38c705', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', '/seed/pipe-after.jpg', 'after', now() - interval '4803038 seconds'),
  ('67f37223-3b6b-4cc9-b303-3b79ff2f0d13', '2a4e8f8b-6380-4835-965f-747935369775', '/seed/chair-before.jpg', 'before', now() - interval '4998490 seconds'),
  ('c17a81fc-4896-496e-8b34-e0fc88c25b59', '2a4e8f8b-6380-4835-965f-747935369775', '/seed/chair-after.jpg', 'after', now() - interval '4928956 seconds'),
  ('a630d4ca-f795-46d0-b104-5c0c873ef3c9', '67a0fd20-d3f6-4c82-81d1-6106deb88775', '/seed/light-before.jpg', 'before', now() - interval '4837343 seconds'),
  ('81b0bbf8-794b-480c-b6e0-6283cc35499f', '67a0fd20-d3f6-4c82-81d1-6106deb88775', '/seed/light-after.jpg', 'after', now() - interval '4754902 seconds'),
  ('37c0b566-871e-47df-80ab-2b178cfbd641', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', '/seed/computer-before.jpg', 'before', now() - interval '4710293 seconds'),
  ('d1db3718-44f7-4a5d-a685-13582cf2b3f4', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', '/seed/computer-after.jpg', 'after', now() - interval '4690470 seconds'),
  ('600f2583-228b-4110-8873-28ad48877a6a', '1080d44d-426e-4799-918b-77623d48d614', '/seed/wall-before.jpg', 'before', now() - interval '4573622 seconds'),
  ('b5f30065-e46a-4cdb-89dc-5b58def346b4', '1080d44d-426e-4799-918b-77623d48d614', '/seed/wall-after.jpg', 'after', now() - interval '4445936 seconds'),
  ('b532c1eb-33cd-4592-85ae-d977460d13e0', '32914f53-981b-4c2b-964e-0bcceabfd971', '/seed/wall-before.jpg', 'before', now() - interval '4485627 seconds'),
  ('623b5a33-3c96-4052-83e9-76d915c06cec', '32914f53-981b-4c2b-964e-0bcceabfd971', '/seed/wall-after.jpg', 'after', now() - interval '4319507 seconds'),
  ('6e175182-cce4-4040-81ac-ef2908f774c3', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', '/seed/chair-before.jpg', 'before', now() - interval '4309962 seconds'),
  ('95ccb185-645c-419e-ae13-eb9e28346642', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', '/seed/chair-after.jpg', 'after', now() - interval '4266396 seconds'),
  ('b1713970-1efb-4ca0-a9c9-62cde1252817', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', '/seed/pipe-before.jpg', 'before', now() - interval '4245545 seconds'),
  ('07a8d175-3ac1-4eb5-a658-3b18706850f3', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', '/seed/pipe-after.jpg', 'after', now() - interval '4082349 seconds'),
  ('d8e1f0eb-60dc-452e-a60e-1ada2a38f3a9', '714752fc-e0e5-4edc-bf2e-98797b32f802', '/seed/wall-before.jpg', 'before', now() - interval '4114395 seconds'),
  ('d207f0d2-b0d1-4e1e-81e8-1ad44981319a', '714752fc-e0e5-4edc-bf2e-98797b32f802', '/seed/wall-after.jpg', 'after', now() - interval '3945131 seconds'),
  ('29c6e5e9-7259-4719-92d5-062c6c6497dd', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', '/seed/wall-before.jpg', 'before', now() - interval '3986396 seconds'),
  ('39eef792-71f5-4d1a-8419-89c3d39b78db', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', '/seed/wall-after.jpg', 'after', now() - interval '3777741 seconds'),
  ('cf8da40d-182f-40d5-8d26-b8330b3da528', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', '/seed/chair-before.jpg', 'before', now() - interval '3822288 seconds'),
  ('c49d902e-849b-47ac-a79a-b4320b08338f', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', '/seed/chair-after.jpg', 'after', now() - interval '3677587 seconds'),
  ('0a1d331f-5314-495b-9f69-9de698f1077b', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', '/seed/wall-before.jpg', 'before', now() - interval '3691501 seconds'),
  ('7a9962d9-b9de-4d1c-a5a6-068378b55e39', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', '/seed/wall-after.jpg', 'after', now() - interval '3552741 seconds'),
  ('fce5d4e0-701c-44ae-96df-f4e792c1469b', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', '/seed/light-before.jpg', 'before', now() - interval '3551910 seconds'),
  ('3eb7eb9a-8c09-4367-91d8-0cf760221c63', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', '/seed/light-after.jpg', 'after', now() - interval '3403824 seconds'),
  ('1d9bff53-7c93-4763-b2b3-8b84d65e671e', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', '/seed/chair-before.jpg', 'before', now() - interval '3429282 seconds'),
  ('01a455fc-2ed7-4fb4-a9e6-55d06b71a0e4', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', '/seed/chair-after.jpg', 'after', now() - interval '3341732 seconds'),
  ('db919d07-ec64-488d-95bd-af624862893f', '308979ed-8ee6-4813-9a32-b4ca5d44182e', '/seed/chair-before.jpg', 'before', now() - interval '3334306 seconds'),
  ('f3b719f4-a2d9-404e-8f4c-8af1e854c364', '308979ed-8ee6-4813-9a32-b4ca5d44182e', '/seed/chair-after.jpg', 'after', now() - interval '3233812 seconds'),
  ('85eea27e-24b2-4e56-b809-141d818ff016', '6dcaab19-e84f-433c-a32c-e2f947049974', '/seed/computer-before.jpg', 'before', now() - interval '3223665 seconds'),
  ('0abdc09f-0214-4fb9-a3aa-2f5279e0f254', '6dcaab19-e84f-433c-a32c-e2f947049974', '/seed/computer-after.jpg', 'after', now() - interval '3129664 seconds'),
  ('1eceb49e-1d69-428c-8f1b-7c42d113ce19', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', '/seed/pipe-before.jpg', 'before', now() - interval '3074791 seconds'),
  ('175e2447-266a-4706-aa33-439503b44f94', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', '/seed/pipe-after.jpg', 'after', now() - interval '2972644 seconds'),
  ('3b30dfe6-c24e-4ce4-8ce8-9832d841c193', '1bb75d56-e04f-4c9c-8215-b7a9cfd0910d', '/seed/light-before.jpg', 'before', now() - interval '2954989 seconds'),
  ('abf19b09-8467-4fb4-832a-83be7f6838c4', 'dc0fb709-d61f-4c59-9e39-2aef773ad342', '/seed/light-before.jpg', 'before', now() - interval '2812682 seconds'),
  ('407c5e6a-e0ce-46b5-8a65-33305615cffd', 'c6121b35-e511-4d2d-af53-4f528f015e65', '/seed/aircon-before.jpg', 'before', now() - interval '2706357 seconds'),
  ('7170b302-b058-4848-8332-a0bed35f62b1', 'c6121b35-e511-4d2d-af53-4f528f015e65', '/seed/aircon-after.jpg', 'after', now() - interval '2591030 seconds'),
  ('8167227a-4429-4c23-806f-4c38bbc66524', '30320fa7-8e59-4e4f-b866-347eb7bca1df', '/seed/pipe-before.jpg', 'before', now() - interval '2564532 seconds'),
  ('e1e836a6-aaf9-44a1-9375-15708d2382b1', '30320fa7-8e59-4e4f-b866-347eb7bca1df', '/seed/pipe-after.jpg', 'after', now() - interval '2438138 seconds'),
  ('b7006937-3615-46a4-82bb-aad37c6546ee', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', '/seed/wall-before.jpg', 'before', now() - interval '104597 seconds'),
  ('9ca6fa6b-1fab-451d-913b-227218c73a13', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', '/seed/wall-after.jpg', 'after', now() - interval '16062 seconds'),
  ('a9fdeeaa-e4fa-4d58-8535-1819a7c67d16', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', '/seed/wall-before.jpg', 'before', now() - interval '85656 seconds'),
  ('0f246c77-a83b-4202-aaf2-eed6bfe456e4', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', '/seed/wall-after.jpg', 'after', now() - interval '9568 seconds'),
  ('4c7527be-27b1-4cbf-b418-bb46f7d0cc0b', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', '/seed/light-before.jpg', 'before', now() - interval '129986 seconds'),
  ('ba8a3fdd-f2da-41a7-918f-8debdd53276c', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', '/seed/light-after.jpg', 'after', now() - interval '66747 seconds'),
  ('cd8a3f1f-6e36-41b5-b1fe-b6e9716d73e1', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', '/seed/computer-before.jpg', 'before', now() - interval '2085223 seconds'),
  ('6d724fb7-af1d-4d66-9105-fe6f0b0bcdc9', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', '/seed/aircon-before.jpg', 'before', now() - interval '1923904 seconds'),
  ('38cf434a-569e-4dbb-a5bc-365fbbd3e01a', '3222fcab-a078-490d-9b5d-fb56b4c4ae8a', '/seed/computer-before.jpg', 'before', now() - interval '1839332 seconds'),
  ('b79512bc-9ed4-4b7b-880c-c627ba3596f1', 'a4d34295-bac0-43fd-9579-57a2604d08f9', '/seed/aircon-before.jpg', 'before', now() - interval '1699223 seconds'),
  ('d6441dcf-b8e9-4d75-be70-a257a4bd3881', 'e76a2af6-7bec-4969-b651-014d525a36ec', '/seed/chair-before.jpg', 'before', now() - interval '1547607 seconds'),
  ('575d6071-08b5-4433-9d51-532d6836a6c5', '1856829a-26d2-4f94-b4e4-bb3f2c7ac617', '/seed/light-before.jpg', 'before', now() - interval '1393797 seconds'),
  ('86a515b6-8173-4c52-a6a5-56f61338ca62', '9f40f755-7765-4de0-9693-ca81fb8aa66f', '/seed/aircon-before.jpg', 'before', now() - interval '1312506 seconds'),
  ('3f4a7ab8-969e-4a59-905f-b3b2a9912347', 'e211a617-8f14-487b-b814-9c341539ba4f', '/seed/pipe-before.jpg', 'before', now() - interval '1189680 seconds'),
  ('7896895d-fe75-40fb-836c-f8c9eae359df', '03161cad-9353-4c6d-ab23-02491153962e', '/seed/aircon-before.jpg', 'before', now() - interval '1031952 seconds'),
  ('5da40043-c3bd-4544-97bc-e7f75cedadb9', '20df381a-5640-4861-ab71-889f1544fa22', '/seed/pipe-before.jpg', 'before', now() - interval '898864 seconds'),
  ('2b5edfc9-a0bc-4316-8097-0ad912f0fdce', 'c7e2610f-7b0e-43e7-8696-5f3833641844', '/seed/pipe-before.jpg', 'before', now() - interval '810538 seconds'),
  ('7b57e30f-7ac4-42f8-bf98-e281d267bc06', '8f8009e8-5f11-4195-923c-df6f4794478e', '/seed/aircon-before.jpg', 'before', now() - interval '699542 seconds'),
  ('1bf67a54-9216-4843-811c-f3223af820ba', '90c384c1-de9c-460f-840e-801f1a06c0b7', '/seed/light-before.jpg', 'before', now() - interval '542832 seconds'),
  ('552cd5de-e3d8-47c0-af27-2239484962f0', '5d8ce707-d593-4dd1-82c2-d8c595cca332', '/seed/aircon-before.jpg', 'before', now() - interval '424186 seconds'),
  ('5aba31db-efee-4aa6-a072-7f9d9cef26f1', '5f3c685b-e8be-4f28-999b-af4e7f307e91', '/seed/wall-before.jpg', 'before', now() - interval '262660 seconds'),
  ('11f41546-e010-41a7-a6ba-8f40d7836bd5', 'b40ff856-0e5d-4fe2-9924-1d5452bd495b', '/seed/wall-before.jpg', 'before', now() - interval '141211 seconds'),
  ('f77e66b6-41c9-4bc7-b605-a5d1c7027ac0', '45055c37-c213-4542-990c-03effd668e0e', '/seed/pipe-before.jpg', 'before', now() - interval '42222 seconds');

insert into status_history (id, request_id, from_status, to_status, actor_id, note, created_at) values
  ('ac08d8be-46e4-47b2-86d3-90a971d17711', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', null, 'pending', '91f675d6-2bf8-4078-834a-fc905fab4da2', null, now() - interval '5090942 seconds'),
  ('1bad4840-2f7e-4d0b-90b9-1ec17065de06', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '5069310 seconds'),
  ('d25e0f65-97a1-4ebf-920b-ab1fd83723bf', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '5061769 seconds'),
  ('cb39b64e-78c6-49d7-bace-51ed6f0e5d0c', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '5041046 seconds'),
  ('29ca2497-b53e-4953-abe7-d16c5f5d972c', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'in_progress', 'waiting_parts', '03139b66-4845-46eb-96ba-0a737abc8095', 'สั่งอะไหล่จากผู้จำหน่ายแล้ว', now() - interval '5024188 seconds'),
  ('f81b577b-0faa-4c38-905e-a9204c9b2d0f', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'waiting_parts', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4824125 seconds'),
  ('a27662f2-bf33-47d2-afae-32ecf7dbff80', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4803038 seconds'),
  ('629ae099-b006-471a-b6cc-f74b069d47bd', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'completed', 'closed', '91f675d6-2bf8-4078-834a-fc905fab4da2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4695150 seconds'),
  ('3241c827-9f61-4077-8fe9-dab2531586a2', '2a4e8f8b-6380-4835-965f-747935369775', null, 'pending', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', null, now() - interval '4998490 seconds'),
  ('473a0fba-6a51-4f7f-bf2f-22737bc9d35b', '2a4e8f8b-6380-4835-965f-747935369775', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4985419 seconds'),
  ('cec4ef2f-ebf9-486b-a3cc-a11340972ea3', '2a4e8f8b-6380-4835-965f-747935369775', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4980964 seconds'),
  ('79eb3c4c-7915-4c84-b8d9-79aa7f08c018', '2a4e8f8b-6380-4835-965f-747935369775', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4953645 seconds'),
  ('84792a8d-0457-44f6-8eec-a81125ef0f01', '2a4e8f8b-6380-4835-965f-747935369775', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4928956 seconds'),
  ('667c60ba-f2ae-4433-9bd3-e9d1cf0e98d3', '2a4e8f8b-6380-4835-965f-747935369775', 'completed', 'closed', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4826030 seconds'),
  ('e17dcaf9-3509-4b07-b461-91e1aaeeaa5d', '67a0fd20-d3f6-4c82-81d1-6106deb88775', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '4837343 seconds'),
  ('8b8f1c4f-7b80-4581-b447-55257147fd4f', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4816621 seconds'),
  ('bdad915b-6268-4c89-8e70-de60a35c28a3', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4808461 seconds'),
  ('42c632c6-2ddc-42fc-ba65-54cb4eff9082', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'assigned', 'in_progress', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '4800077 seconds'),
  ('401b284e-9a75-47dc-b870-1b174540b51e', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'in_progress', 'completed', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '4754902 seconds'),
  ('e855bd8d-9f3c-44e7-9b43-997818d3989c', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'completed', 'closed', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4647887 seconds'),
  ('03d8772b-7369-48ec-a467-43b401ea7cec', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '4710293 seconds'),
  ('7b6480c6-75a8-47d9-9105-ccfb35d45fb1', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4706925 seconds'),
  ('02957266-0728-4914-bd5b-9a8a9a8c6a79', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4701964 seconds'),
  ('b45e2417-e5a4-4ad3-80d2-96cedda910fe', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '4697237 seconds'),
  ('fa821ebb-2fc5-4231-8e43-f9e9dc81c713', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'in_progress', 'completed', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '4690470 seconds'),
  ('b25d8a98-3f97-422e-afd4-1803feebd8e8', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'completed', 'closed', 'ed42646d-e662-45ad-9029-03ede427fdbe', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4554788 seconds'),
  ('09863f84-5520-4843-b07d-fc90a06a4a75', '1080d44d-426e-4799-918b-77623d48d614', null, 'pending', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', null, now() - interval '4573622 seconds'),
  ('c46a7c42-a3a4-419b-9f45-d46a457fef49', '1080d44d-426e-4799-918b-77623d48d614', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4549010 seconds'),
  ('6018ae82-8305-4860-a776-0d82f760d24b', '1080d44d-426e-4799-918b-77623d48d614', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4541452 seconds'),
  ('1f42f070-26eb-4993-a893-3378a9fec9f9', '1080d44d-426e-4799-918b-77623d48d614', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4482516 seconds'),
  ('017a16d3-f7da-4d2c-986b-6145590f6123', '1080d44d-426e-4799-918b-77623d48d614', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4445936 seconds'),
  ('aa21f561-f893-43c9-9211-b44dea879978', '1080d44d-426e-4799-918b-77623d48d614', 'completed', 'closed', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4366117 seconds'),
  ('eb983eb4-0783-4081-8862-4ea114b40c86', '32914f53-981b-4c2b-964e-0bcceabfd971', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '4485627 seconds'),
  ('ebca92ee-59e6-4dbc-a930-5e545fc6a6c4', '32914f53-981b-4c2b-964e-0bcceabfd971', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4472806 seconds'),
  ('21d886aa-64de-4ec3-b26e-258211c92b78', '32914f53-981b-4c2b-964e-0bcceabfd971', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4462857 seconds'),
  ('7941eee6-50d2-49ca-84c4-ede0093ca3b4', '32914f53-981b-4c2b-964e-0bcceabfd971', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4414708 seconds'),
  ('e0d2ebd3-3179-414b-97b0-3d658e5e9401', '32914f53-981b-4c2b-964e-0bcceabfd971', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4319507 seconds'),
  ('c020276c-414d-49c9-ba34-a04a96cd39d3', '32914f53-981b-4c2b-964e-0bcceabfd971', 'completed', 'closed', '117fb892-4d82-4137-ba29-69aa2028da00', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4229860 seconds'),
  ('11d984dd-b66f-4d3e-8711-4ce3be1aaea4', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', null, 'pending', '91f675d6-2bf8-4078-834a-fc905fab4da2', null, now() - interval '4309962 seconds'),
  ('88e5d14e-eee9-4eaa-8e7b-84632a6d6ee2', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4307965 seconds'),
  ('913c9759-ae86-4373-a3cd-8bb6c6c51a3c', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4303582 seconds'),
  ('fc261771-da93-47a0-9a8e-bf0a3ee536d0', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4287033 seconds'),
  ('4491cf86-fe4e-4e6b-88ea-94cc5ab7e6e6', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4266396 seconds'),
  ('f5eb7bb8-886e-4c92-a79b-3b32545dc3a3', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'completed', 'closed', '91f675d6-2bf8-4078-834a-fc905fab4da2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4142115 seconds'),
  ('093b0cc6-f858-4668-ad2a-b78018e87d58', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '4245545 seconds'),
  ('a2248594-a0e4-4ff6-b36e-15e312f4d8ad', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4227452 seconds'),
  ('bc08611a-a0cc-42cf-b4d1-13ad8f920c6b', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4214312 seconds'),
  ('20d984a0-4e17-4012-b11c-1d974aa8ad83', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4169524 seconds'),
  ('514b39f1-4841-4262-a94a-278a650ace1e', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4082349 seconds'),
  ('abd4c63e-0cc7-42f7-8e06-321242b2a9b8', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'completed', 'closed', '117fb892-4d82-4137-ba29-69aa2028da00', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4077909 seconds'),
  ('5f95c731-e87a-4cbb-ac9b-990c77bd6eb5', '714752fc-e0e5-4edc-bf2e-98797b32f802', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '4114395 seconds'),
  ('44b9a519-2bca-4b3c-9105-17da61e1e000', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4108094 seconds'),
  ('0b330dce-7ad0-42b5-b9d4-c0ad1192d439', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '4103673 seconds'),
  ('d25f0e8b-3aa7-41de-8747-b5c00db3dd56', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '4050160 seconds'),
  ('d12c6ebf-d17b-49e9-ab91-b58b10d7e705', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3945131 seconds'),
  ('26238fc2-526a-405a-aad9-7dbe454ab204', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'completed', 'closed', '117fb892-4d82-4137-ba29-69aa2028da00', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3899483 seconds'),
  ('310d5996-7d21-4262-a5ea-7b99fd68637f', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', null, 'pending', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', null, now() - interval '3986396 seconds'),
  ('e2bd4aff-e331-4ed4-b44c-6ed4a98f4728', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3982933 seconds'),
  ('62846911-10cd-4fe5-add9-6866e40a5246', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3968874 seconds'),
  ('696a8afc-f286-42a6-b193-b38ededa196c', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3963949 seconds'),
  ('80e5386a-d5be-4bd4-acb0-da52c53f9645', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'in_progress', 'waiting_parts', '03139b66-4845-46eb-96ba-0a737abc8095', 'สั่งอะไหล่จากผู้จำหน่ายแล้ว', now() - interval '3954214 seconds'),
  ('3eef753b-9e52-433b-8bac-5c09fe3a4cd5', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'waiting_parts', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3847197 seconds'),
  ('8aa2b02a-8e6e-4586-9e1f-b849e170b94e', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3777741 seconds'),
  ('172a573c-6785-41c9-92d2-8928f718db73', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'completed', 'closed', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3718202 seconds'),
  ('d0565f25-9a1d-4612-b87b-95efc448896e', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '3822288 seconds'),
  ('7d271220-4e00-4fe6-8685-20ec58608650', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3798069 seconds'),
  ('b1a53f11-b239-49e5-b8f7-5907cef61479', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3786326 seconds'),
  ('724401df-5eeb-4307-928f-d3f9976c0b4f', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3761098 seconds'),
  ('4230657f-c57a-4ff8-bdb4-fecca28b5e5b', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3677587 seconds'),
  ('616ba81a-428f-4668-af42-d773e01e5c67', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'completed', 'closed', 'ed42646d-e662-45ad-9029-03ede427fdbe', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3506993 seconds'),
  ('87e86eba-d5fe-4489-9992-74c29b6317be', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', null, 'pending', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', null, now() - interval '3691501 seconds'),
  ('62a48509-bf53-4c25-bad4-9df8f1667608', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3675589 seconds'),
  ('48719e75-a099-4748-a1ea-e9a4e0124fd8', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3661864 seconds'),
  ('f919a01d-f7b5-4ce3-8557-5c161d8e3ca8', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3598942 seconds'),
  ('f3580cdc-8612-497e-a40b-bde8361867c6', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3552741 seconds'),
  ('f2037049-1ead-4725-a443-ebb9841b0c47', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'completed', 'closed', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3413829 seconds'),
  ('f77fc967-2f7f-431c-b1c1-ff0d0856baf6', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', null, 'pending', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', null, now() - interval '3551910 seconds'),
  ('d969fa36-26bc-4854-9cd0-b10b22a18386', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3527710 seconds'),
  ('6af2579e-56ec-4739-a5a1-99c12b3701a4', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3519180 seconds'),
  ('3af6956a-4ab5-43bb-af38-f198b0b45893', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '3494737 seconds'),
  ('d841d792-ad8f-4638-91e1-eaf2f21a7f0a', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'in_progress', 'completed', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '3403824 seconds'),
  ('0a3d78c8-12de-499c-8942-bc1947d8950b', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'completed', 'closed', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3392993 seconds'),
  ('ec30a0d8-389d-44bb-a12e-e4f87a195baa', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '3429282 seconds'),
  ('b7a9d020-c2f5-42f5-9584-d361b78300d0', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3419958 seconds'),
  ('7fccdf4b-e43a-4233-91bc-1650e54cdfd5', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3415257 seconds'),
  ('2891ef16-0a48-48e0-a154-24503a7757da', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3387073 seconds'),
  ('8d60ad2d-f9ed-4885-a2d5-a5356af36c70', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3341732 seconds'),
  ('00b48e16-4e0c-49da-9634-8a39377c050e', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'completed', 'closed', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3313020 seconds'),
  ('a9ffae0c-44ec-40ee-9e34-d3ef869ee120', '308979ed-8ee6-4813-9a32-b4ca5d44182e', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '3334306 seconds'),
  ('fa52159d-070c-4ab2-8806-c3bf13eb3236', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3332341 seconds'),
  ('5f7915c9-eee9-4c3f-8502-6718545f0eaa', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3323359 seconds'),
  ('335bffbe-3091-4b23-a86c-67f21dc10117', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3321470 seconds'),
  ('26dc54e6-28ad-4585-9b78-4b6972e205a9', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3233812 seconds'),
  ('80e0e155-51f7-447b-8ba5-e79669590ef5', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'completed', 'closed', '117fb892-4d82-4137-ba29-69aa2028da00', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3087095 seconds'),
  ('f5d8d8e8-df89-4e0b-bfae-feec12e42258', '6dcaab19-e84f-433c-a32c-e2f947049974', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '3223665 seconds'),
  ('53ad97f4-aebc-4f7b-9521-dfa0e1aa4490', '6dcaab19-e84f-433c-a32c-e2f947049974', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3220953 seconds'),
  ('376a2f03-65e7-4864-8816-f91a83fe8345', '6dcaab19-e84f-433c-a32c-e2f947049974', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3207387 seconds'),
  ('db154c18-05a2-4a91-bf13-4c72c9b7b89b', '6dcaab19-e84f-433c-a32c-e2f947049974', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '3204476 seconds'),
  ('2220a5c0-b657-4f01-92c4-8aba4b2ea045', '6dcaab19-e84f-433c-a32c-e2f947049974', 'in_progress', 'completed', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '3129664 seconds'),
  ('078437f6-8dc5-4ef3-879d-42f6af0d2270', '6dcaab19-e84f-433c-a32c-e2f947049974', 'completed', 'closed', 'ed42646d-e662-45ad-9029-03ede427fdbe', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2920638 seconds'),
  ('4ef935fa-cc89-4557-a434-11132b4cc9bc', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '3074791 seconds'),
  ('12be024c-fa2b-43d1-86bd-32b36c3a1fc8', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3057813 seconds'),
  ('34f31c1c-75b5-4cd1-a5f8-a1fe81eb3bae', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '3045225 seconds'),
  ('b3b5b463-6d7b-4a2e-b9e7-1e66d6012a71', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '3002504 seconds'),
  ('3ba5327d-662b-4615-ba14-5d7be690e60b', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '2972644 seconds'),
  ('8d5927aa-facc-4a2f-b941-697cadb6c201', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'completed', 'closed', 'ed42646d-e662-45ad-9029-03ede427fdbe', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2870749 seconds'),
  ('c5893ea5-ba57-4efb-a588-0a76e22b2d28', '1bb75d56-e04f-4c9c-8215-b7a9cfd0910d', null, 'pending', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', null, now() - interval '2954989 seconds'),
  ('4c9dfa52-6eba-40ec-85fb-5406c79084e4', '1bb75d56-e04f-4c9c-8215-b7a9cfd0910d', 'pending', 'cancelled', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 'แก้ไขได้เองแล้ว', now() - interval '2952982 seconds'),
  ('c2d98831-51fd-44b1-9751-2b4e86907e9a', 'dc0fb709-d61f-4c59-9e39-2aef773ad342', null, 'pending', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', null, now() - interval '2812682 seconds'),
  ('53834ede-d711-4696-bf93-f4c23f22f46a', 'dc0fb709-d61f-4c59-9e39-2aef773ad342', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2810618 seconds'),
  ('add1f191-4753-4d4d-b713-9f22f14f2146', 'dc0fb709-d61f-4c59-9e39-2aef773ad342', 'accepted', 'rejected', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', now() - interval '2804577 seconds'),
  ('227ba5d0-eb4e-4d77-aed0-5344fcb926a3', 'c6121b35-e511-4d2d-af53-4f528f015e65', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '2706357 seconds'),
  ('6cd7d1e7-566d-4714-9ed9-a0e3ac20cca2', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2689671 seconds'),
  ('102b050d-4536-460b-932b-7697b9e86b31', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2681438 seconds'),
  ('97b3dfae-bc6a-4de3-ba9e-33821383f813', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'assigned', 'in_progress', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '2655584 seconds'),
  ('ae2b711b-f6e3-4172-b44a-d371ff4b19e9', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'in_progress', 'completed', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '2591030 seconds'),
  ('5391dda8-64cd-423b-8483-a3aa35e01d3f', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'completed', 'closed', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2407669 seconds'),
  ('596b7b1b-d87a-4018-813a-10e98bc4d326', '30320fa7-8e59-4e4f-b866-347eb7bca1df', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '2564532 seconds'),
  ('dc150241-4dd0-447c-8176-0e2b0047415c', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2550580 seconds'),
  ('0ae3055c-dcc3-4651-b556-2b848a1a5d11', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2536244 seconds'),
  ('ba6fc5a0-67b8-4790-b18a-c82699a0595b', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '2528652 seconds'),
  ('f6061bd7-8bf8-4785-80bf-7d32f249f9f6', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '2438138 seconds'),
  ('96ab4463-c8c3-43a8-8914-05dc4635e8d5', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'completed', 'closed', '117fb892-4d82-4137-ba29-69aa2028da00', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2277540 seconds'),
  ('874e88c4-dcf6-46b5-89ea-9039c99d4abd', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', null, 'pending', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', null, now() - interval '104597 seconds'),
  ('aac87d3d-61f8-4d5c-a3be-4208b8efe365', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '102113 seconds'),
  ('aa8c2946-fc20-4be2-9d56-4b4f91006951', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '89177 seconds'),
  ('738389da-ffca-464b-bcd1-2ea7ed8c594e', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '61247 seconds'),
  ('c65cca4d-d2a1-4a46-be86-f2bb853e3c3e', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'in_progress', 'completed', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '16062 seconds'),
  ('0f13e5c5-4bed-4fe6-85b7-a3426ec251fb', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '85656 seconds'),
  ('7b7d4f9f-14a4-4f44-ba54-adf5e217105d', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '66319 seconds'),
  ('cc0d0da6-87c5-4e2d-a703-63ea61c16c5b', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '63363 seconds'),
  ('d4fd55f1-7fd8-44cb-a5ed-425b188f1500', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '44187 seconds'),
  ('3efdb70c-f23d-423a-b592-63d1bbc2df83', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'in_progress', 'completed', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '9568 seconds'),
  ('4243c4fd-d21d-49e6-b878-42d5ecede3a9', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', null, 'pending', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', null, now() - interval '129986 seconds'),
  ('2cb41887-5c20-4fde-a228-44310e7b5707', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '118467 seconds'),
  ('68f0ab02-035e-4a8f-9c0a-8828ba100ca5', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '112646 seconds'),
  ('f54aaaea-6e05-40d4-8338-1f04c97c65e9', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '110057 seconds'),
  ('c45e4fae-afff-43d9-a383-a15c3640e71c', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'in_progress', 'completed', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '66747 seconds'),
  ('1dce26c6-2994-426f-b113-b9545ed591bf', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '2085223 seconds'),
  ('22532dea-b01a-45b6-8a17-2a26d796d5d4', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2072993 seconds'),
  ('46fe6c74-a0b6-485f-8f7c-ba3b6a703402', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '2071566 seconds'),
  ('b7e68e86-b37b-4857-86e6-866216baf855', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '2066247 seconds'),
  ('b908bd22-0af0-4fc0-9bfa-7f6f377a00f3', 'adf498a9-3ed0-4542-bcf3-4844bf374f2d', 'in_progress', 'waiting_parts', '0c36e328-4637-433d-a9c7-2480e1448e42', 'รออะไหล่จากผู้จำหน่าย 2-3 วัน', now() - interval '2048533 seconds'),
  ('51dbd3f7-ef46-4dca-a3e4-bbac8c8e89fc', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '1923904 seconds'),
  ('ca7b8982-3680-47d8-82a7-3311b50a828a', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1921746 seconds'),
  ('6790e1dd-1b67-4746-a1b2-99dc83296e96', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1910035 seconds'),
  ('0b6268ce-2fac-4902-85a6-b38d8d736137', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', 'assigned', 'in_progress', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '1900970 seconds'),
  ('1c7ccb82-342d-4520-aef6-89c19b1ee519', 'd84b516b-2ed1-41b9-9f57-b93d3f0d0c24', 'in_progress', 'waiting_parts', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', 'รออะไหล่จากผู้จำหน่าย 2-3 วัน', now() - interval '1875365 seconds'),
  ('0a5c1eae-b4cf-4774-9f76-1d61bd68b5fc', '3222fcab-a078-490d-9b5d-fb56b4c4ae8a', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '1839332 seconds'),
  ('f6b0a53e-36c1-404d-a841-2e2ad939c144', '3222fcab-a078-490d-9b5d-fb56b4c4ae8a', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1815754 seconds'),
  ('e0cb8d20-1da4-411f-a200-5a977251ac88', '3222fcab-a078-490d-9b5d-fb56b4c4ae8a', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1810957 seconds'),
  ('ad8d950b-67f5-4818-9d6f-add88fc78100', '3222fcab-a078-490d-9b5d-fb56b4c4ae8a', 'assigned', 'in_progress', '0c36e328-4637-433d-a9c7-2480e1448e42', null, now() - interval '1790944 seconds'),
  ('64d8f5fa-19ef-46b5-86a9-8a5f0aef21bd', 'a4d34295-bac0-43fd-9579-57a2604d08f9', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '1699223 seconds'),
  ('b6fd739f-bb6c-43ba-997b-0680273d7f03', 'a4d34295-bac0-43fd-9579-57a2604d08f9', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1680473 seconds'),
  ('66ebcb3c-fbdc-4789-bb5b-1e7f87c31ccd', 'a4d34295-bac0-43fd-9579-57a2604d08f9', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1668055 seconds'),
  ('5d431285-6927-4c37-bed1-63c324ff9851', 'a4d34295-bac0-43fd-9579-57a2604d08f9', 'assigned', 'in_progress', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', null, now() - interval '1599313 seconds'),
  ('126d515a-2314-4c43-9ae5-937f2cece5af', 'e76a2af6-7bec-4969-b651-014d525a36ec', null, 'pending', '2d9bebdc-3f35-431a-bdb9-6d8f57a697be', null, now() - interval '1547607 seconds'),
  ('826e4292-e816-4d5b-a0bb-19dbb256b9b1', 'e76a2af6-7bec-4969-b651-014d525a36ec', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1545829 seconds'),
  ('7bb9eb1b-2acf-4239-8944-5778fbfda6f1', 'e76a2af6-7bec-4969-b651-014d525a36ec', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1539771 seconds'),
  ('8e081759-e481-4d4a-8cc5-d79febdd5e53', 'e76a2af6-7bec-4969-b651-014d525a36ec', 'assigned', 'in_progress', '03139b66-4845-46eb-96ba-0a737abc8095', null, now() - interval '1532939 seconds'),
  ('83c5cca2-38f1-4e18-b0f6-6e059d7d285d', '1856829a-26d2-4f94-b4e4-bb3f2c7ac617', null, 'pending', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', null, now() - interval '1393797 seconds'),
  ('18d6b4df-ff3d-41ce-9bf6-55ef13088896', '1856829a-26d2-4f94-b4e4-bb3f2c7ac617', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1380210 seconds'),
  ('1797375c-aa36-4136-b6a8-dba4394f8761', '1856829a-26d2-4f94-b4e4-bb3f2c7ac617', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1368304 seconds'),
  ('e4915971-de6f-47a3-85f9-a149c875a6a1', '9f40f755-7765-4de0-9693-ca81fb8aa66f', null, 'pending', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', null, now() - interval '1312506 seconds'),
  ('b06d3edd-191c-408c-a84c-28596a57ffaf', '9f40f755-7765-4de0-9693-ca81fb8aa66f', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1285592 seconds'),
  ('f70fe518-df33-4143-8018-da013695db83', '9f40f755-7765-4de0-9693-ca81fb8aa66f', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1284623 seconds'),
  ('f6dba53f-622e-4bd4-b989-241b61251576', 'e211a617-8f14-487b-b814-9c341539ba4f', null, 'pending', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', null, now() - interval '1189680 seconds'),
  ('f23f93ce-9ac3-40bd-99d9-dd38b85b56cd', 'e211a617-8f14-487b-b814-9c341539ba4f', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1179577 seconds'),
  ('8d50adf9-240a-4989-8ad4-c657b5f1d605', 'e211a617-8f14-487b-b814-9c341539ba4f', 'accepted', 'assigned', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1171885 seconds'),
  ('8b1c661e-4b53-4819-991e-11193b968746', '03161cad-9353-4c6d-ab23-02491153962e', null, 'pending', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', null, now() - interval '1031952 seconds'),
  ('d924ac83-8637-4174-85a7-2f383bf2bf1f', '03161cad-9353-4c6d-ab23-02491153962e', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '1030749 seconds'),
  ('daef4ad6-34c1-4c65-abe9-4a5fe692c841', '20df381a-5640-4861-ab71-889f1544fa22', null, 'pending', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', null, now() - interval '898864 seconds'),
  ('4e6143d4-5129-42cc-9639-15679f392fd4', '20df381a-5640-4861-ab71-889f1544fa22', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '895566 seconds'),
  ('e942552f-30da-40e8-99a6-5a4ffe4994e8', 'c7e2610f-7b0e-43e7-8696-5f3833641844', null, 'pending', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', null, now() - interval '810538 seconds'),
  ('f377a110-3184-438a-ae17-a732d0df9730', 'c7e2610f-7b0e-43e7-8696-5f3833641844', 'pending', 'need_info', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', 'ช่วยระบุหมายเลขเครื่องหรือแนบรูปมุมกว้างเพิ่มเติม', now() - interval '808078 seconds'),
  ('c50d1e6b-f6ff-426d-80e0-f0573969c152', '8f8009e8-5f11-4195-923c-df6f4794478e', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '699542 seconds'),
  ('65b52237-320e-478b-8ef4-be4ec3d13e10', '8f8009e8-5f11-4195-923c-df6f4794478e', 'pending', 'cancelled', '117fb892-4d82-4137-ba29-69aa2028da00', 'แก้ไขได้เองแล้ว', now() - interval '695847 seconds'),
  ('c9a6a573-2b71-4294-907c-69dc660ee43d', '90c384c1-de9c-460f-840e-801f1a06c0b7', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '542832 seconds'),
  ('c16c992e-2abf-4cda-ae5a-dc0772d4cd24', '90c384c1-de9c-460f-840e-801f1a06c0b7', 'pending', 'accepted', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', null, now() - interval '535458 seconds'),
  ('6cdf5eba-1d9f-4d2c-821b-812e8bf164c0', '90c384c1-de9c-460f-840e-801f1a06c0b7', 'accepted', 'rejected', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', now() - interval '521703 seconds'),
  ('8c635af1-bae4-47e1-9daf-a2bc6a23313d', '5d8ce707-d593-4dd1-82c2-d8c595cca332', null, 'pending', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', null, now() - interval '424186 seconds'),
  ('9dac6d01-3b66-45cd-8b05-098ebd71deae', '5f3c685b-e8be-4f28-999b-af4e7f307e91', null, 'pending', '117fb892-4d82-4137-ba29-69aa2028da00', null, now() - interval '262660 seconds'),
  ('8516e1fc-5310-46ad-864b-d68b502f238b', 'b40ff856-0e5d-4fe2-9924-1d5452bd495b', null, 'pending', '91f675d6-2bf8-4078-834a-fc905fab4da2', null, now() - interval '141211 seconds'),
  ('0aace02d-3280-4ea9-a35c-b7518b3a7fd7', '45055c37-c213-4542-990c-03effd668e0e', null, 'pending', 'ed42646d-e662-45ad-9029-03ede427fdbe', null, now() - interval '42222 seconds');

insert into repair_notes (id, request_id, cause, parts_used, technician_id, created_at) values
  ('b5feae3c-2758-417a-8fb6-9640bc8b8838', 'c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 'ลูกลอยชักโครกค้าง', 'ชุดลูกลอย 1 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4803038 seconds'),
  ('3e8d68b3-1877-48a9-9672-99071cb3f716', '2a4e8f8b-6380-4835-965f-747935369775', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4928956 seconds'),
  ('fb8ead5b-81e9-4c07-a4b2-2c0a692688b1', '67a0fd20-d3f6-4c82-81d1-6106deb88775', 'สายไฟในเต้ารับหลวม', 'เต้ารับคู่ 1 ชุด', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', now() - interval '4754902 seconds'),
  ('9bc82930-581e-414a-9301-6d356da19076', 'b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 'Power supply เสีย', 'Power supply 500W 1 ตัว', '0c36e328-4637-433d-a9c7-2480e1448e42', now() - interval '4690470 seconds'),
  ('cd50d464-6c8f-4f6c-97d4-5d275b7a471d', '1080d44d-426e-4799-918b-77623d48d614', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4445936 seconds'),
  ('1844a4f3-6844-4231-a6e3-6fe57ca11ffb', '32914f53-981b-4c2b-964e-0bcceabfd971', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4319507 seconds'),
  ('d9eab8e7-741f-4793-a9dc-04bac30c1888', '2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4266396 seconds'),
  ('088c2ee1-5f69-462e-b181-9d218d888472', 'f60f665d-ffd2-4764-a0a4-c30c830fcf56', 'ซีลยางในก๊อกเสื่อม', 'ซีลยาง 2 ชิ้น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '4082349 seconds'),
  ('594776ab-eaff-4b21-9788-9a9663d31c33', '714752fc-e0e5-4edc-bf2e-98797b32f802', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3945131 seconds'),
  ('1d66b6ad-945c-4d37-81ef-1bea20891129', '0fbf623d-b981-4bcc-97e0-5c6a3db1d8b9', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3777741 seconds'),
  ('84ed81e4-4e17-42e9-b725-c1002af52788', 'af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3677587 seconds'),
  ('ad4cdf49-091f-4ad4-9606-3a726048aabc', 'f130ec87-da99-4cb1-bb7c-77a338cf480c', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3552741 seconds'),
  ('35419130-fc1a-4bf8-a3c6-1b5b64620ec3', '7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 'สายไฟในเต้ารับหลวม', 'เต้ารับคู่ 1 ชุด', '0c36e328-4637-433d-a9c7-2480e1448e42', now() - interval '3403824 seconds'),
  ('4446b3a0-f5d0-4ad2-847d-eac55cfc0a7f', '1d30d31d-60ce-42a4-93bc-ab70b62a6062', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3341732 seconds'),
  ('5568acd3-214e-458c-b37c-ee5c79cf87d0', '308979ed-8ee6-4813-9a32-b4ca5d44182e', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '3233812 seconds'),
  ('87607b72-0b4b-4799-897f-9913749e1248', '6dcaab19-e84f-433c-a32c-e2f947049974', 'สาย HDMI ในรางชำรุด', 'สาย HDMI 10 ม. 1 เส้น', '0c36e328-4637-433d-a9c7-2480e1448e42', now() - interval '3129664 seconds'),
  ('e4672aa8-4399-44a4-aa95-ebb721c474bf', '55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 'ซีลยางในก๊อกเสื่อม', 'ซีลยาง 2 ชิ้น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '2972644 seconds'),
  ('b8458340-aaa4-4e3b-9437-fe7970edc1ae', 'c6121b35-e511-4d2d-af53-4f528f015e65', 'น้ำยาแอร์รั่วและคอยล์ร้อนสกปรก', 'น้ำยา R32 1 กก.', '84ecc920-c6f8-40e5-8923-be0daffbc0c0', now() - interval '2591030 seconds'),
  ('309ce7e3-a1d4-4e68-927f-721b7cd2d3fc', '30320fa7-8e59-4e4f-b866-347eb7bca1df', 'ลูกลอยชักโครกค้าง', 'ชุดลูกลอย 1 ชุด', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '2438138 seconds'),
  ('b02c6c53-8684-4a2c-a175-7acf6242338d', '7164ab9f-39d5-4432-a142-d9bc37f8dad7', 'ประสานหน่วยงานที่เกี่ยวข้องดำเนินการเรียบร้อย', null, '0c36e328-4637-433d-a9c7-2480e1448e42', now() - interval '16062 seconds'),
  ('a8c79961-6534-4ed0-a5e6-b79f8b697f13', '1a58d285-13b9-48e1-9110-00bdf1ce7d08', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '03139b66-4845-46eb-96ba-0a737abc8095', now() - interval '9568 seconds'),
  ('b2bc8798-2b4d-481a-9037-a2f2beabe218', 'e78bae0a-1143-492a-8b0b-1e5a3bc32319', 'บัลลาสต์หลอดไฟเสื่อม', 'บัลลาสต์อิเล็กทรอนิกส์ 2 ตัว, หลอด LED T8 2 หลอด', '0c36e328-4637-433d-a9c7-2480e1448e42', now() - interval '66747 seconds');

insert into info_requests (id, request_id, asked_by, question, answer, answered_at, created_at) values
  ('a25e9495-db15-4561-a537-56e5c224ea60', 'c7e2610f-7b0e-43e7-8696-5f3833641844', 'd840e44a-ed29-4fd1-b5d1-9bc826243b96', 'ช่วยระบุหมายเลขเครื่องหรือแนบรูปมุมกว้างเพิ่มเติม', null, null, now() - interval '808078 seconds');

insert into ratings (request_id, score, comment, created_at) values
  ('c98dbbfe-69f0-48a5-bb6e-39efc4e03460', 5, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '4695150 seconds'),
  ('2a4e8f8b-6380-4835-965f-747935369775', 3, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '4826030 seconds'),
  ('67a0fd20-d3f6-4c82-81d1-6106deb88775', 5, null, now() - interval '4647887 seconds'),
  ('b07bc440-1c4a-4e54-90a6-76be4cde2fcc', 5, null, now() - interval '4554788 seconds'),
  ('1080d44d-426e-4799-918b-77623d48d614', 5, null, now() - interval '4366117 seconds'),
  ('32914f53-981b-4c2b-964e-0bcceabfd971', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '4229860 seconds'),
  ('2e0fb4bc-77f9-4a44-8c97-d4c1981c3487', 5, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '4142115 seconds'),
  ('714752fc-e0e5-4edc-bf2e-98797b32f802', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '3899483 seconds'),
  ('af3c7e07-4a0d-4595-8d48-6d6cbcb2d7f0', 5, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '3506993 seconds'),
  ('f130ec87-da99-4cb1-bb7c-77a338cf480c', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '3413829 seconds'),
  ('7bbff41f-2158-42af-b9a2-109ee4ec9ba0', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '3392993 seconds'),
  ('1d30d31d-60ce-42a4-93bc-ab70b62a6062', 5, null, now() - interval '3313020 seconds'),
  ('308979ed-8ee6-4813-9a32-b4ca5d44182e', 4, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '3087095 seconds'),
  ('6dcaab19-e84f-433c-a32c-e2f947049974', 5, null, now() - interval '2920638 seconds'),
  ('55d4c1d6-ff22-4d81-a2c2-f9d83e9d9a0c', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '2870749 seconds'),
  ('c6121b35-e511-4d2d-af53-4f528f015e65', 5, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '2407669 seconds'),
  ('30320fa7-8e59-4e4f-b866-347eb7bca1df', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '2277540 seconds');

insert into notifications (id, user_id, request_id, type, title, body, read_at, created_at) values
  ('23f55062-4ea8-4c5f-a70c-5c90055b2b03', 'b0763cd6-5ca0-4d7b-b611-a3e4c38282f8', '1856829a-26d2-4f94-b4e4-bb3f2c7ac617', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0004 · อาคาร CAMT ห้อง 102', null, now() - interval '1368304 seconds'),
  ('91093cef-48bc-447a-a989-b7d37a90eee2', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', '9f40f755-7765-4de0-9693-ca81fb8aa66f', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0005 · อาคาร CAMT ห้อง 304', now() - interval '3 seconds', now() - interval '1284623 seconds'),
  ('9be767b2-efd9-496d-9506-2dd4fd01763d', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 'e211a617-8f14-487b-b814-9c341539ba4f', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0006 · อาคารเรียนรวม ห้อง 202', now() - interval '3 seconds', now() - interval '1171885 seconds'),
  ('913b642d-80f3-4189-9c2f-6c9b3ed63963', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', '03161cad-9353-4c6d-ab23-02491153962e', 'accepted', 'รับเรื่องแล้ว', 'คำร้อง MR-2609-0007 · อาคารเรียนรวม ห้อง 305', null, now() - interval '1030749 seconds'),
  ('bda260f6-4a99-4110-ae8d-695ec4598552', '05aa3735-cc54-4582-865c-ebb5d0c2a6e7', '20df381a-5640-4861-ab71-889f1544fa22', 'accepted', 'รับเรื่องแล้ว', 'คำร้อง MR-2609-0008 · อาคารคณะวิศวกรรมศาสตร์ 30 ปี ห้อง 402', null, now() - interval '895566 seconds'),
  ('fc49de12-57ca-4a60-8678-c3de63c3b0e9', '6a87577b-3dd4-472a-9bf6-3cb9a8b73926', 'c7e2610f-7b0e-43e7-8696-5f3833641844', 'need_info', 'ขอข้อมูลเพิ่มเติม', 'คำร้อง MR-2609-0009 · อาคารคณะพยาบาลศาสตร์ ห้อง 204', now() - interval '3 seconds', now() - interval '808078 seconds'),
  ('9c7e3a4e-f852-4645-a2a7-2bf21478b808', '117fb892-4d82-4137-ba29-69aa2028da00', '8f8009e8-5f11-4195-923c-df6f4794478e', 'cancelled', 'ยกเลิก', 'คำร้อง MR-2609-0010 · อาคารเรียนรวม ห้อง 205', now() - interval '3 seconds', now() - interval '695847 seconds'),
  ('287e588b-3bf9-46a3-a050-aeb2525c59f7', '117fb892-4d82-4137-ba29-69aa2028da00', '90c384c1-de9c-460f-840e-801f1a06c0b7', 'rejected', 'ปฏิเสธ', 'คำร้อง MR-2609-0011 · อาคารคณะพยาบาลศาสตร์ ห้อง 204', now() - interval '3 seconds', now() - interval '521703 seconds'),
  ('5b0e2135-8183-4bcd-8e9b-e7bbdae45d61', '631af0fb-1c6b-4a4e-adf2-d70792cd19cc', '5d8ce707-d593-4dd1-82c2-d8c595cca332', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0012 · อาคารคณะวิศวกรรมศาสตร์ 30 ปี ห้อง 401', now() - interval '3 seconds', now() - interval '424186 seconds'),
  ('21a09315-faae-4e51-be93-22936b15cfe0', '117fb892-4d82-4137-ba29-69aa2028da00', '5f3c685b-e8be-4f28-999b-af4e7f307e91', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0013 · อาคารเรียนรวม ห้อง 202', now() - interval '3 seconds', now() - interval '262660 seconds'),
  ('3b254e80-8892-4fcf-a0bd-46c65e9ff3fc', '91f675d6-2bf8-4078-834a-fc905fab4da2', 'b40ff856-0e5d-4fe2-9924-1d5452bd495b', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0014 · อาคารคณะพยาบาลศาสตร์ ห้อง 102', null, now() - interval '141211 seconds'),
  ('65731662-3236-467f-a6ed-021011f8d1f8', 'ed42646d-e662-45ad-9029-03ede427fdbe', '45055c37-c213-4542-990c-03effd668e0e', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0015 · หอพักนักศึกษา 5 ห้อง 102', null, now() - interval '42222 seconds');

select setval(pg_get_serial_sequence('"SmartCMU".categories', 'id'), (select coalesce(max(id), 1) from categories));
select setval(pg_get_serial_sequence('"SmartCMU".campuses', 'id'), (select coalesce(max(id), 1) from campuses));
select setval(pg_get_serial_sequence('"SmartCMU".buildings', 'id'), (select coalesce(max(id), 1) from buildings));
select setval(pg_get_serial_sequence('"SmartCMU".rooms', 'id'), (select coalesce(max(id), 1) from rooms));

-- Next: run db/supabase-app-role.sql to create the app's own login role for this schema.
