-- Smart CMU Maintenance: one-shot Supabase setup (schema + storage bucket + demo data).
-- Paste into Supabase → SQL Editor → Run. Safe to re-run: it clears existing app data first.
-- Generated by scripts/export-setup-sql.ts — do not edit by hand.
-- All tables are created in schema "SmartCMU" (identifier is case-sensitive).

create schema if not exists "SmartCMU";
set search_path to "SmartCMU", public, extensions;

-- ===== 001_init.sql =====
-- Smart CMU Maintenance Request System — initial schema
-- Works on Supabase Postgres and on plain Postgres 15+ (and PGlite for local dev).

-- gen_random_uuid() is built into Postgres 13+, no extension needed.

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('reporter', 'technician', 'admin')),
  full_name text not null default '',
  user_type text check (user_type in ('student', 'staff')),
  faculty text,
  phone text,
  profile_completed boolean not null default false,
  pdpa_accepted_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id serial primary key,
  name_th text not null,
  icon text not null default 'Wrench',
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table if not exists technician_skills (
  technician_id uuid not null references users(id) on delete cascade,
  category_id int not null references categories(id) on delete cascade,
  primary key (technician_id, category_id)
);

create table if not exists campuses (
  id serial primary key,
  name_th text not null
);

create table if not exists buildings (
  id serial primary key,
  campus_id int not null references campuses(id) on delete cascade,
  name_th text not null
);

create table if not exists rooms (
  id serial primary key,
  building_id int not null references buildings(id) on delete cascade,
  floor int not null,
  name_th text not null
);

create table if not exists request_code_counters (
  yymm text primary key,
  last_value int not null
);

create table if not exists requests (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  reporter_id uuid not null references users(id),
  category_id int not null references categories(id),
  room_id int not null references rooms(id),
  landmark text,
  description text not null,
  urgency text not null default 'normal' check (urgency in ('low', 'normal', 'urgent')),
  status text not null default 'pending' check (status in (
    'pending', 'accepted', 'assigned', 'in_progress', 'waiting_parts', 'need_info',
    'completed', 'closed', 'cancelled', 'rejected', 'reopened'
  )),
  status_before_info text,
  assigned_technician_id uuid references users(id),
  merged_into_id uuid references requests(id),
  reject_reason text,
  reopen_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  closed_at timestamptz
);

create index if not exists requests_reporter_idx on requests(reporter_id);
create index if not exists requests_technician_idx on requests(assigned_technician_id);
create index if not exists requests_status_idx on requests(status);
create index if not exists requests_room_category_idx on requests(room_id, category_id);
create index if not exists requests_created_idx on requests(created_at);

create table if not exists request_images (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  url text not null,
  kind text not null check (kind in ('before', 'after')),
  created_at timestamptz not null default now()
);

create table if not exists request_followers (
  request_id uuid not null references requests(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, user_id)
);

create table if not exists status_history (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  from_status text,
  to_status text not null,
  actor_id uuid references users(id),
  note text,
  created_at timestamptz not null default now()
);
create index if not exists status_history_request_idx on status_history(request_id, created_at);

create table if not exists repair_notes (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  cause text not null,
  parts_used text,
  technician_id uuid references users(id),
  created_at timestamptz not null default now()
);

create table if not exists info_requests (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references requests(id) on delete cascade,
  asked_by uuid references users(id),
  question text not null,
  answer text,
  answered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists ratings (
  request_id uuid primary key references requests(id) on delete cascade,
  score int not null check (score between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  request_id uuid references requests(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on notifications(user_id, created_at desc);

-- The app talks to Postgres from the server only (service connection).
-- Lock the tables away from Supabase's public anon/authenticated API roles.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'alter table users enable row level security';
    execute 'alter table categories enable row level security';
    execute 'alter table technician_skills enable row level security';
    execute 'alter table campuses enable row level security';
    execute 'alter table buildings enable row level security';
    execute 'alter table rooms enable row level security';
    execute 'alter table request_code_counters enable row level security';
    execute 'alter table requests enable row level security';
    execute 'alter table request_images enable row level security';
    execute 'alter table request_followers enable row level security';
    execute 'alter table status_history enable row level security';
    execute 'alter table repair_notes enable row level security';
    execute 'alter table info_requests enable row level security';
    execute 'alter table ratings enable row level security';
    execute 'alter table notifications enable row level security';
  end if;
end $$;

-- ===== 002_supabase_storage.sql =====
-- Supabase only: public bucket for request photos (skipped on plain Postgres / PGlite).
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'storage' and table_name = 'buckets') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('request-images', 'request-images', true, 1258291, array['image/jpeg', 'image/png'])
    on conflict (id) do nothing;
  end if;
end $$;

-- ===== 003_performance.sql =====
-- Indexes for the queries every page runs.
create index if not exists requests_autoclose_idx on requests(completed_at) where status = 'completed';
create index if not exists request_followers_user_idx on request_followers(user_id);
create index if not exists notifications_unread_idx on notifications(user_id) where read_at is null;
create index if not exists requests_updated_idx on requests(updated_at desc);

-- ===== demo data =====
truncate users, categories, technician_skills, campuses, buildings, rooms, request_code_counters, requests, request_images, request_followers, status_history, repair_notes, info_requests, ratings, notifications restart identity cascade;

insert into users (id, username, password_hash, role, full_name, user_type, faculty, phone, profile_completed, pdpa_accepted_at, is_active, created_at) values
  ('8bb156cf-dfe6-478a-8987-6b6763cbfb6a', 'pojnicha.t', '$2b$10$szDKBe5x4jFldYYMc/XFtODfdKNbNOfgMT5AHShI.AOdFQtSB6TAO', 'technician', 'พจน์ณิชา ทองย้อย', 'staff', null, '0891112203', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('c0f61d6b-cf5f-491f-b096-abae9aaa147b', 'supawika.n', '$2b$10$X3cS1jpeYPLc7zwFQ8wIi..aNscsgs6fGcTnfFw0x7AluBBuodJ6K', 'reporter', 'สุภาวิกา นันทสุวรรณ', 'staff', 'สำนักหอสมุด', '0812345615', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('e7f8ceab-cf38-4559-827e-c8d8be6bb239', 'trirat.j', '$2b$10$4OUV2TmXV.NYRCHNFFJhmOJyPB5Gjhuq8FDITd8YGQD0opHP59Oc2', 'reporter', 'ตรีรัตน์ จอมพันธ์', 'staff', 'กองกิจการนักศึกษา', '0812345616', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('00e1f9cd-3c8b-4016-8255-64442b85ee51', 'staff01', '$2b$10$EEMvleeen.tSyG.fLD6E.OuMZpoNoTbQgx4s2ObLDfU8yetOs.SjK', 'reporter', 'ศิริพร คำแสน', 'staff', 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี (CAMT)', '0812345601', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('0a799853-dae1-4d68-a895-053babb791a8', 'student03', '$2b$10$VWNwp9s8Wpa9rSjfIN986OQ/0BVfRW5ZoczkY3rljhipcarlBv2wK', 'reporter', 'กมลชนก อินทร์แก้ว', 'student', 'คณะวิศวกรรมศาสตร์', '0812345611', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('0a85ef20-b774-47b1-b241-eee6670f3495', 'student05', '$2b$10$eVAsE4veD1/7Lg8pcCZn3.G.8.9ZWpqDw/88xmqnZQkmFcb1RsM8m', 'reporter', 'พิมพ์ชนก ทองดี', 'student', 'คณะแพทยศาสตร์', '0812345613', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('252eeae1-34a5-4582-a2d1-bf0638d96249', 'tech02', '$2b$10$dCjx6hT.QnzEuc27vhf1Zu8mWEcdawAbJuFAe0UwQbTk2j8pYde0S', 'technician', 'วิชัย ศรีสุข', null, null, '0891112202', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('5b3abd49-a767-4b9a-b40a-6adc9ee926db', 'student02', '$2b$10$TibD2go4NRN6qTK9bEZLhObhbzczVsv5U4yzrqUtQf6T4aa2nruFe', 'reporter', 'ณัฐวุฒิ ปัญญาดี', 'student', 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี (CAMT)', '0812345610', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('90919f40-45dc-40f4-91f9-50b8ceeba531', 'student04', '$2b$10$FRDW0wfZ.q6zASws2v5cn.WSarCOJWEpVaNIm92YnF7FGi3DoY0GC', 'reporter', 'ภูริภัทร สายสุวรรณ', 'student', 'คณะบริหารธุรกิจ', '0812345612', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('9cfbf32c-ee8e-42c9-a961-00ca40921462', 'admin01', '$2b$10$tkD5vv/BKYEwGGkVYocMnOwiCwiAtr5tkrfoC6B3sPW91Qd93GLzy', 'admin', 'พรทิพย์ วงศ์ใหญ่', null, null, '053941000', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('b1be67ba-6252-4385-bcab-00ffc2b5af46', 'tech01', '$2b$10$tIiN1B8f7Px1Xw0hJndyYeLU41wgsq9a8kHO73gf/x0idiSimO.5e', 'technician', 'สมศักดิ์ ใจดี', null, null, '0891112201', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('ec2c0905-6030-4f78-82b1-47bb91c66df2', 'student06', '$2b$10$.f3AKtPEWBU3JtSPpTpxy.pltC68VZQAcyZJ35q9ybMROY.fVXgOK', 'reporter', 'ธนภัทร มณีวงศ์', 'student', 'คณะพยาบาลศาสตร์', '0812345614', true, now() - interval '7781307 seconds', true, now() - interval '5307 seconds'),
  ('1646cbd3-d59f-4d86-b9fa-f24829bc0d37', 'panicha_sr', '$2b$10$zZxYmQ2f0yDfELjdCVVCr.jnOpCGqUNOwhMzy3uimS1TvvYoo7OFa', 'reporter', 'ภานิชา ศรีกระจ่าง', 'student', 'วิทยาลัยศิลปะ สื่อ และเทคโนโลยี (CAMT)', '0951386174', true, now() - interval '772 seconds', true, now() - interval '5307 seconds');

insert into categories (id, name_th, icon, is_active, sort_order) values
  (1, 'ไฟฟ้า', 'Zap', true, 0),
  (2, 'ประปา', 'Droplets', true, 1),
  (3, 'เครื่องปรับอากาศ', 'AirVent', true, 2),
  (4, 'อุปกรณ์ IT', 'Monitor', true, 3),
  (5, 'เฟอร์นิเจอร์', 'Armchair', true, 4),
  (6, 'อาคารและสถานที่', 'Building2', true, 5),
  (7, 'อื่น ๆ', 'Ellipsis', true, 6);

insert into technician_skills (technician_id, category_id) values
  ('b1be67ba-6252-4385-bcab-00ffc2b5af46', 1),
  ('b1be67ba-6252-4385-bcab-00ffc2b5af46', 3),
  ('252eeae1-34a5-4582-a2d1-bf0638d96249', 2),
  ('252eeae1-34a5-4582-a2d1-bf0638d96249', 6),
  ('252eeae1-34a5-4582-a2d1-bf0638d96249', 5),
  ('8bb156cf-dfe6-478a-8987-6b6763cbfb6a', 4),
  ('8bb156cf-dfe6-478a-8987-6b6763cbfb6a', 7),
  ('8bb156cf-dfe6-478a-8987-6b6763cbfb6a', 1);

insert into campuses (id, name_th) values
  (1, 'วิทยาเขตสวนสัก'),
  (2, 'วิทยาเขตสวนดอก'),
  (3, 'วิทยาเขตแม่เหียะ');

insert into buildings (id, campus_id, name_th) values
  (1, 1, 'อาคาร CAMT'),
  (2, 1, 'อาคารเรียนรวม'),
  (3, 1, 'สำนักหอสมุด'),
  (4, 1, 'หอพักนักศึกษา 5'),
  (5, 1, 'อาคารคณะวิศวกรรมศาสตร์ 30 ปี'),
  (6, 2, 'อาคารเรียนรวม คณะแพทยศาสตร์'),
  (7, 2, 'อาคารคณะพยาบาลศาสตร์'),
  (8, 2, 'หอพักนักศึกษาแพทย์'),
  (9, 3, 'อาคารศูนย์ประชุม'),
  (10, 3, 'อาคารปฏิบัติการวิจัย');

insert into rooms (id, building_id, floor, name_th) values
  (1, 1, 1, 'ห้อง 101'),
  (2, 1, 1, 'ห้อง 102'),
  (3, 1, 1, 'ห้อง 103'),
  (4, 1, 1, 'ห้อง 104'),
  (5, 1, 2, 'ห้อง 201'),
  (6, 1, 2, 'ห้อง 202'),
  (7, 1, 2, 'ห้อง 203'),
  (8, 1, 2, 'ห้อง 204'),
  (9, 1, 3, 'ห้อง 301'),
  (10, 1, 3, 'ห้อง 302'),
  (11, 1, 3, 'ห้อง 303'),
  (12, 1, 3, 'ห้อง 304'),
  (13, 1, 4, 'ห้อง 401'),
  (14, 1, 4, 'ห้อง 402'),
  (15, 1, 4, 'ห้อง 403'),
  (16, 1, 4, 'ห้อง 404'),
  (17, 1, 5, 'ห้อง 501'),
  (18, 1, 5, 'ห้อง 502'),
  (19, 1, 5, 'ห้อง 503'),
  (20, 1, 5, 'ห้อง 504'),
  (21, 2, 1, 'ห้อง 101'),
  (22, 2, 1, 'ห้อง 102'),
  (23, 2, 1, 'ห้อง 103'),
  (24, 2, 1, 'ห้อง 104'),
  (25, 2, 1, 'ห้อง 105'),
  (26, 2, 2, 'ห้อง 201'),
  (27, 2, 2, 'ห้อง 202'),
  (28, 2, 2, 'ห้อง 203'),
  (29, 2, 2, 'ห้อง 204'),
  (30, 2, 2, 'ห้อง 205'),
  (31, 2, 3, 'ห้อง 301'),
  (32, 2, 3, 'ห้อง 302'),
  (33, 2, 3, 'ห้อง 303'),
  (34, 2, 3, 'ห้อง 304'),
  (35, 2, 3, 'ห้อง 305'),
  (36, 2, 4, 'ห้อง 401'),
  (37, 2, 4, 'ห้อง 402'),
  (38, 2, 4, 'ห้อง 403'),
  (39, 2, 4, 'ห้อง 404'),
  (40, 2, 4, 'ห้อง 405'),
  (41, 3, 1, 'ห้อง 101'),
  (42, 3, 1, 'ห้อง 102'),
  (43, 3, 1, 'ห้อง 103'),
  (44, 3, 2, 'ห้อง 201'),
  (45, 3, 2, 'ห้อง 202'),
  (46, 3, 2, 'ห้อง 203'),
  (47, 3, 3, 'ห้อง 301'),
  (48, 3, 3, 'ห้อง 302'),
  (49, 3, 3, 'ห้อง 303'),
  (50, 4, 1, 'ห้อง 101'),
  (51, 4, 1, 'ห้อง 102'),
  (52, 4, 1, 'ห้อง 103'),
  (53, 4, 1, 'ห้อง 104'),
  (54, 4, 2, 'ห้อง 201'),
  (55, 4, 2, 'ห้อง 202'),
  (56, 4, 2, 'ห้อง 203'),
  (57, 4, 2, 'ห้อง 204'),
  (58, 4, 3, 'ห้อง 301'),
  (59, 4, 3, 'ห้อง 302'),
  (60, 4, 3, 'ห้อง 303'),
  (61, 4, 3, 'ห้อง 304'),
  (62, 4, 4, 'ห้อง 401'),
  (63, 4, 4, 'ห้อง 402'),
  (64, 4, 4, 'ห้อง 403'),
  (65, 4, 4, 'ห้อง 404'),
  (66, 5, 1, 'ห้อง 101'),
  (67, 5, 1, 'ห้อง 102'),
  (68, 5, 1, 'ห้อง 103'),
  (69, 5, 1, 'ห้อง 104'),
  (70, 5, 2, 'ห้อง 201'),
  (71, 5, 2, 'ห้อง 202'),
  (72, 5, 2, 'ห้อง 203'),
  (73, 5, 2, 'ห้อง 204'),
  (74, 5, 3, 'ห้อง 301'),
  (75, 5, 3, 'ห้อง 302'),
  (76, 5, 3, 'ห้อง 303'),
  (77, 5, 3, 'ห้อง 304'),
  (78, 5, 4, 'ห้อง 401'),
  (79, 5, 4, 'ห้อง 402'),
  (80, 5, 4, 'ห้อง 403'),
  (81, 5, 4, 'ห้อง 404'),
  (82, 6, 1, 'ห้อง 101'),
  (83, 6, 1, 'ห้อง 102'),
  (84, 6, 1, 'ห้อง 103'),
  (85, 6, 1, 'ห้อง 104'),
  (86, 6, 2, 'ห้อง 201'),
  (87, 6, 2, 'ห้อง 202'),
  (88, 6, 2, 'ห้อง 203'),
  (89, 6, 2, 'ห้อง 204'),
  (90, 6, 3, 'ห้อง 301'),
  (91, 6, 3, 'ห้อง 302'),
  (92, 6, 3, 'ห้อง 303'),
  (93, 6, 3, 'ห้อง 304'),
  (94, 6, 4, 'ห้อง 401'),
  (95, 6, 4, 'ห้อง 402'),
  (96, 6, 4, 'ห้อง 403'),
  (97, 6, 4, 'ห้อง 404'),
  (98, 7, 1, 'ห้อง 101'),
  (99, 7, 1, 'ห้อง 102'),
  (100, 7, 1, 'ห้อง 103'),
  (101, 7, 1, 'ห้อง 104'),
  (102, 7, 2, 'ห้อง 201'),
  (103, 7, 2, 'ห้อง 202'),
  (104, 7, 2, 'ห้อง 203'),
  (105, 7, 2, 'ห้อง 204'),
  (106, 7, 3, 'ห้อง 301'),
  (107, 7, 3, 'ห้อง 302'),
  (108, 7, 3, 'ห้อง 303'),
  (109, 7, 3, 'ห้อง 304'),
  (110, 8, 1, 'ห้อง 101'),
  (111, 8, 1, 'ห้อง 102'),
  (112, 8, 1, 'ห้อง 103'),
  (113, 8, 2, 'ห้อง 201'),
  (114, 8, 2, 'ห้อง 202'),
  (115, 8, 2, 'ห้อง 203'),
  (116, 8, 3, 'ห้อง 301'),
  (117, 8, 3, 'ห้อง 302'),
  (118, 8, 3, 'ห้อง 303'),
  (119, 8, 4, 'ห้อง 401'),
  (120, 8, 4, 'ห้อง 402'),
  (121, 8, 4, 'ห้อง 403'),
  (122, 9, 1, 'ห้อง 101'),
  (123, 9, 1, 'ห้อง 102'),
  (124, 9, 1, 'ห้อง 103'),
  (125, 9, 2, 'ห้อง 201'),
  (126, 9, 2, 'ห้อง 202'),
  (127, 9, 2, 'ห้อง 203'),
  (128, 10, 1, 'ห้อง 101'),
  (129, 10, 1, 'ห้อง 102'),
  (130, 10, 1, 'ห้อง 103'),
  (131, 10, 2, 'ห้อง 201'),
  (132, 10, 2, 'ห้อง 202'),
  (133, 10, 2, 'ห้อง 203'),
  (134, 10, 3, 'ห้อง 301'),
  (135, 10, 3, 'ห้อง 302'),
  (136, 10, 3, 'ห้อง 303');

insert into request_code_counters (yymm, last_value) values
  ('2607', 8),
  ('2608', 18),
  ('2609', 17);

insert into requests (id, code, reporter_id, category_id, room_id, landmark, description, urgency, status, status_before_info, assigned_technician_id, merged_into_id, reject_reason, reopen_count, created_at, updated_at, completed_at, closed_at) values
  ('674c9958-5d9c-419f-9a05-9a6d451fa38f', 'MR-2607-0001', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', 2, 33, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '5096246 seconds', now() - interval '4700454 seconds', now() - interval '4808342 seconds', now() - interval '4700454 seconds'),
  ('a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'MR-2607-0002', '0a85ef20-b774-47b1-b241-eee6670f3495', 5, 88, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'low', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '5003794 seconds', now() - interval '4831334 seconds', now() - interval '4934260 seconds', now() - interval '4831334 seconds'),
  ('1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'MR-2607-0003', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 1, 47, 'โต๊ะแถวสุดท้ายฝั่งหน้าต่าง', 'ปลั๊กไฟใต้โต๊ะแถวหลังไม่มีไฟ เสียบชาร์จโน้ตบุ๊กไม่ได้', 'normal', 'closed', null, 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, null, 0, now() - interval '4842647 seconds', now() - interval '4653191 seconds', now() - interval '4760206 seconds', now() - interval '4653191 seconds'),
  ('1460f660-3038-43cb-93bb-bc47d09121f4', 'MR-2607-0004', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 4, 2, null, 'ไมโครโฟนไร้สายมีเสียงซ่า ใช้สอนไม่ได้', 'urgent', 'closed', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '4715597 seconds', now() - interval '4560092 seconds', now() - interval '4695774 seconds', now() - interval '4560092 seconds'),
  ('ffb70f07-e42b-4db4-ba12-a7679dc09912', 'MR-2607-0005', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 6, 56, 'มุมห้องด้านหลัง', 'ฝ้าเพดานมีรอยน้ำซึมและเริ่มโป่ง กลัวจะหล่นลงมา', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '4578926 seconds', now() - interval '4371421 seconds', now() - interval '4451240 seconds', now() - interval '4371421 seconds'),
  ('5c7e3322-a7ae-4241-af38-4902ea4ee267', 'MR-2607-0006', '0a799853-dae1-4d68-a895-053babb791a8', 6, 54, 'หน้าบันไดหนีไฟ', 'กระเบื้องพื้นทางเดินแตกและยกตัว เดินสะดุดง่าย', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '4490931 seconds', now() - interval '4235164 seconds', now() - interval '4324811 seconds', now() - interval '4235164 seconds'),
  ('99960563-0997-41bf-8634-8672821efa38', 'MR-2607-0007', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', 5, 62, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'low', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '4315266 seconds', now() - interval '4147419 seconds', now() - interval '4271700 seconds', now() - interval '4147419 seconds'),
  ('8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'MR-2607-0008', '0a799853-dae1-4d68-a895-053babb791a8', 2, 78, 'ห้องน้ำชาย ห้องสุดท้าย', 'ชักโครกกดน้ำไม่ลง น้ำไหลค้างในถัง', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '4250849 seconds', now() - interval '4083213 seconds', now() - interval '4087653 seconds', now() - interval '4083213 seconds'),
  ('cc0f486a-b377-44df-91ca-b1c2974067e9', 'MR-2608-0001', '0a799853-dae1-4d68-a895-053babb791a8', 6, 35, null, 'ผนังมีรอยร้าวยาวตั้งแต่ขอบหน้าต่างลงมา', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '4119699 seconds', now() - interval '3904787 seconds', now() - interval '3950435 seconds', now() - interval '3904787 seconds'),
  ('43846eb4-30d9-4eab-8174-e625717b0627', 'MR-2608-0002', '0a85ef20-b774-47b1-b241-eee6670f3495', 6, 13, 'หน้าบันไดหนีไฟ', 'กระเบื้องพื้นทางเดินแตกและยกตัว เดินสะดุดง่าย', 'urgent', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3991700 seconds', now() - interval '3723506 seconds', now() - interval '3783045 seconds', now() - interval '3723506 seconds'),
  ('74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'MR-2608-0003', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 5, 17, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3827592 seconds', now() - interval '3512297 seconds', now() - interval '3682891 seconds', now() - interval '3512297 seconds'),
  ('0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'MR-2608-0004', '90919f40-45dc-40f4-91f9-50b8ceeba531', 6, 75, 'ประตูหลัง', 'ประตูห้องปิดไม่ได้ ลูกบิดชำรุด', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3696805 seconds', now() - interval '3419133 seconds', now() - interval '3558045 seconds', now() - interval '3419133 seconds'),
  ('cb3dff46-f3dd-4d59-b346-321999565092', 'MR-2608-0005', '0a85ef20-b774-47b1-b241-eee6670f3495', 1, 35, 'โต๊ะแถวสุดท้ายฝั่งหน้าต่าง', 'ปลั๊กไฟใต้โต๊ะแถวหลังไม่มีไฟ เสียบชาร์จโน้ตบุ๊กไม่ได้', 'normal', 'closed', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '3557214 seconds', now() - interval '3398297 seconds', now() - interval '3409128 seconds', now() - interval '3398297 seconds'),
  ('38202e2b-9cd8-4060-b063-1790c36eee8c', 'MR-2608-0006', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 5, 62, 'ตู้หลังห้อง', 'ประตูตู้เก็บของหลุดจากบานพับ', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3434586 seconds', now() - interval '3318324 seconds', now() - interval '3347036 seconds', now() - interval '3318324 seconds'),
  ('b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'MR-2608-0007', '0a799853-dae1-4d68-a895-053babb791a8', 5, 125, null, 'โต๊ะเรียนขาโยก เขียนหนังสือลำบาก', 'urgent', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3339610 seconds', now() - interval '3092399 seconds', now() - interval '3239116 seconds', now() - interval '3092399 seconds'),
  ('54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'MR-2608-0008', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 4, 16, 'แถวที่ 3 เครื่องที่ 12', 'คอมพิวเตอร์เครื่องที่ 12 เปิดไม่ติด ไฟไม่เข้า', 'urgent', 'closed', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '3228969 seconds', now() - interval '2925942 seconds', now() - interval '3134968 seconds', now() - interval '2925942 seconds'),
  ('5fae4862-4002-4118-9a0d-05aa67e2db09', 'MR-2608-0009', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 2, 21, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '3080095 seconds', now() - interval '2876053 seconds', now() - interval '2977948 seconds', now() - interval '2876053 seconds'),
  ('1f807261-f2df-40b2-bafd-6a5e632eebb0', 'MR-2608-0010', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 1, 1, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'normal', 'cancelled', null, null, null, null, 0, now() - interval '2960293 seconds', now() - interval '2958286 seconds', null, null),
  ('f6062bae-f596-43d6-bc0c-e1d199d95b1c', 'MR-2608-0011', '0a85ef20-b774-47b1-b241-eee6670f3495', 1, 131, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'urgent', 'rejected', null, null, null, 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', 0, now() - interval '2817986 seconds', now() - interval '2809881 seconds', null, null),
  ('45c5b233-294d-48dd-9591-993521cb969d', 'MR-2608-0012', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 3, 1, 'เครื่องฝั่งหน้าต่าง', 'แอร์เปิดแล้วไม่เย็น มีแต่ลมออก นักศึกษานั่งเรียนร้อนมาก', 'normal', 'closed', null, 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, null, 0, now() - interval '2711661 seconds', now() - interval '2412973 seconds', now() - interval '2596334 seconds', now() - interval '2412973 seconds'),
  ('0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'MR-2608-0013', '0a799853-dae1-4d68-a895-053babb791a8', 2, 108, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'normal', 'closed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '2569836 seconds', now() - interval '2282844 seconds', now() - interval '2443442 seconds', now() - interval '2282844 seconds'),
  ('0dfce590-ed62-4417-b3db-89a56de9618c', 'MR-2609-0001', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 7, 25, null, 'ป้ายบอกทางหนีไฟหลุดออกจากผนัง', 'normal', 'completed', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '109901 seconds', now() - interval '21366 seconds', now() - interval '21366 seconds', null),
  ('e433cfda-040b-4362-9a59-82b703a07a3f', 'MR-2609-0002', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 6, 55, 'ประตูหลัง', 'ประตูห้องปิดไม่ได้ ลูกบิดชำรุด', 'normal', 'completed', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '90960 seconds', now() - interval '14872 seconds', now() - interval '14872 seconds', null),
  ('07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'MR-2609-0003', '90919f40-45dc-40f4-91f9-50b8ceeba531', 1, 28, 'ข้างประตูทางเข้า', 'สวิตช์ไฟหน้าห้องหลวม กดแล้วมีประกายไฟ', 'normal', 'completed', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '135290 seconds', now() - interval '72051 seconds', now() - interval '72051 seconds', null),
  ('881c967a-13f6-4e44-ad80-2778bd006d55', 'MR-2608-0014', '0a799853-dae1-4d68-a895-053babb791a8', 4, 38, null, 'ไมโครโฟนไร้สายมีเสียงซ่า ใช้สอนไม่ได้', 'normal', 'waiting_parts', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '2090527 seconds', now() - interval '2053837 seconds', null, null),
  ('360616c9-07b3-4a7a-8921-bfcf7af3b736', 'MR-2608-0015', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 3, 1, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'urgent', 'waiting_parts', null, 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, null, 0, now() - interval '1929208 seconds', now() - interval '1880669 seconds', null, null),
  ('02ed23f7-ae00-4468-a4d3-aa66b16613f2', 'MR-2608-0016', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 4, 45, null, 'Wi-Fi @JumboPlus หลุดบ่อยในห้องนี้ เชื่อมต่อไม่ได้เกือบทั้งห้อง', 'normal', 'in_progress', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '1844636 seconds', now() - interval '1796248 seconds', null, null),
  ('223996ec-e82f-4700-a592-956d7de07e7a', 'MR-2608-0017', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 3, 87, null, 'รีโมตแอร์หาย และตั้งอุณหภูมิที่ตัวเครื่องไม่ได้', 'normal', 'in_progress', null, 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, null, 0, now() - interval '1704527 seconds', now() - interval '1604617 seconds', null, null),
  ('75bf5214-dd4f-42e9-b736-dc456af3b733', 'MR-2608-0018', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 5, 118, 'แถวหลังฝั่งขวา', 'เก้าอี้พนักพิงหักหลายตัว นั่งแล้วไม่ปลอดภัย', 'urgent', 'in_progress', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '1552911 seconds', now() - interval '1538243 seconds', null, null),
  ('ac36eace-f141-43c0-b0ff-8e63ba382d5d', 'MR-2609-0004', '0a85ef20-b774-47b1-b241-eee6670f3495', 1, 2, 'ทางเดินหน้าลิฟต์', 'ไฟทางเดินกะพริบตลอดเวลา ตอนกลางคืนมองไม่ค่อยเห็น', 'normal', 'assigned', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, null, 0, now() - interval '1399101 seconds', now() - interval '1373608 seconds', null, null),
  ('42afe6af-769a-428b-955c-528fd1988f95', 'MR-2609-0005', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 3, 12, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'normal', 'assigned', null, 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, null, 0, now() - interval '1317810 seconds', now() - interval '1289927 seconds', null, null),
  ('fa72e107-5809-4815-924a-1b5b97a70cfc', 'MR-2609-0006', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 2, 27, 'ห้องน้ำชาย ห้องสุดท้าย', 'ชักโครกกดน้ำไม่ลง น้ำไหลค้างในถัง', 'normal', 'assigned', null, '252eeae1-34a5-4582-a2d1-bf0638d96249', null, null, 0, now() - interval '1194984 seconds', now() - interval '1177189 seconds', null, null),
  ('9d9cf0ff-2085-42b7-8dfe-c9248f15b483', 'MR-2609-0007', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 3, 35, null, 'รีโมตแอร์หาย และตั้งอุณหภูมิที่ตัวเครื่องไม่ได้', 'normal', 'accepted', null, null, null, null, 0, now() - interval '1037256 seconds', now() - interval '1036053 seconds', null, null),
  ('b89eb69d-36f9-4844-ba60-a7507023245e', 'MR-2609-0008', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 2, 79, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'urgent', 'accepted', null, null, null, null, 0, now() - interval '904168 seconds', now() - interval '900870 seconds', null, null),
  ('d4bbb595-ea17-4957-925a-788352263633', 'MR-2609-0009', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 2, 105, null, 'น้ำไหลอ่อนมากทั้งชั้น เปิดก๊อกแล้วแทบไม่มีน้ำ', 'low', 'need_info', 'pending', null, null, null, 0, now() - interval '815842 seconds', now() - interval '813382 seconds', null, null),
  ('285257da-22df-4790-9ba5-549ea638c36a', 'MR-2609-0010', '0a799853-dae1-4d68-a895-053babb791a8', 3, 30, 'เหนือโต๊ะแถวที่ 3', 'แอร์มีน้ำหยดลงบนโต๊ะเรียน ต้องย้ายที่นั่ง', 'normal', 'cancelled', null, null, null, null, 0, now() - interval '704846 seconds', now() - interval '701151 seconds', null, null),
  ('8d68ff50-6221-4b63-8567-71b5e5fb9cfc', 'MR-2609-0011', '0a799853-dae1-4d68-a895-053babb791a8', 1, 105, 'ทางเดินหน้าลิฟต์', 'ไฟทางเดินกะพริบตลอดเวลา ตอนกลางคืนมองไม่ค่อยเห็น', 'normal', 'rejected', null, null, null, 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', 0, now() - interval '548136 seconds', now() - interval '527007 seconds', null, null),
  ('06e2842f-d84d-4ad7-b18a-e17a00fddfac', 'MR-2609-0012', '90919f40-45dc-40f4-91f9-50b8ceeba531', 3, 78, null, 'แอร์มีเสียงดังผิดปกติเวลาเปิด เหมือนมีอะไรกระทบใบพัด', 'normal', 'pending', null, null, null, null, 0, now() - interval '429490 seconds', now() - interval '429490 seconds', null, null),
  ('32dca21b-e58c-4537-8008-27554be35286', 'MR-2609-0013', '0a799853-dae1-4d68-a895-053babb791a8', 6, 27, 'มุมห้องด้านหลัง', 'ฝ้าเพดานมีรอยน้ำซึมและเริ่มโป่ง กลัวจะหล่นลงมา', 'low', 'pending', null, null, null, null, 0, now() - interval '267964 seconds', now() - interval '267964 seconds', null, null),
  ('20a5fe77-e836-4ab8-9e14-6aa9d66cade2', 'MR-2609-0014', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', 7, 99, 'หน้าทางเข้าหลัก', 'มีรังผึ้งขนาดใหญ่ใต้ชายคาหน้าอาคาร นักศึกษาเดินผ่านบ่อย', 'normal', 'pending', null, null, null, null, 0, now() - interval '146515 seconds', now() - interval '146515 seconds', null, null),
  ('238c135c-6766-45f2-8512-92346272a6fc', 'MR-2609-0015', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 2, 51, 'ห้องแพนทรี', 'ท่อใต้อ่างล้างจานรั่ว มีน้ำนองพื้น เสี่ยงลื่น', 'normal', 'pending', null, null, null, null, 0, now() - interval '47526 seconds', now() - interval '47526 seconds', null, null),
  ('da7f3fb0-bf70-41be-aeb2-9d093f04f397', 'MR-2609-0016', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', 4, 11, null, 'คอมเปิดไม่ติด', 'normal', 'pending', null, null, null, null, 0, now() - interval '686 seconds', now() - interval '686 seconds', null, null),
  ('bf633342-773a-41de-844c-4f2d8416a799', 'MR-2609-0017', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', 3, 10, null, 'แอร์ไม่เย็น', 'normal', 'pending', null, null, null, null, 0, now() - interval '393 seconds', now() - interval '393 seconds', null, null);

insert into request_images (id, request_id, url, kind, created_at) values
  ('9ba68965-cff0-4fb5-b8e2-bd4960d1b46b', '674c9958-5d9c-419f-9a05-9a6d451fa38f', '/seed/pipe-before.jpg', 'before', now() - interval '5096246 seconds'),
  ('16711950-2c05-4a1e-963b-3fa188a353a3', '674c9958-5d9c-419f-9a05-9a6d451fa38f', '/seed/pipe-after.jpg', 'after', now() - interval '4808342 seconds'),
  ('6943367b-9df5-42ba-b333-30a197b85031', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', '/seed/chair-before.jpg', 'before', now() - interval '5003794 seconds'),
  ('71e959dc-5acf-4b79-bff8-7b0550fbfc19', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', '/seed/chair-after.jpg', 'after', now() - interval '4934260 seconds'),
  ('ff280d07-e436-4f3a-a786-1aafae88493d', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', '/seed/light-before.jpg', 'before', now() - interval '4842647 seconds'),
  ('47e231b6-41bc-4c24-ae2d-4228cad7d644', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', '/seed/light-after.jpg', 'after', now() - interval '4760206 seconds'),
  ('566789f3-0e3c-424d-8cbe-5904f49c19d6', '1460f660-3038-43cb-93bb-bc47d09121f4', '/seed/computer-before.jpg', 'before', now() - interval '4715597 seconds'),
  ('a0f84e64-df2f-4740-877e-b59e980b6bb8', '1460f660-3038-43cb-93bb-bc47d09121f4', '/seed/computer-after.jpg', 'after', now() - interval '4695774 seconds'),
  ('43e040b4-ea91-480f-99c4-0af33cab1120', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', '/seed/wall-before.jpg', 'before', now() - interval '4578926 seconds'),
  ('83a591e6-594c-4fae-88b7-fc14bb8e9c7b', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', '/seed/wall-after.jpg', 'after', now() - interval '4451240 seconds'),
  ('27c350bc-cb6d-4b9a-8b38-9859c7c4e1be', '5c7e3322-a7ae-4241-af38-4902ea4ee267', '/seed/wall-before.jpg', 'before', now() - interval '4490931 seconds'),
  ('92ec96b1-74ad-4941-919e-58fb62475128', '5c7e3322-a7ae-4241-af38-4902ea4ee267', '/seed/wall-after.jpg', 'after', now() - interval '4324811 seconds'),
  ('0d850006-55dc-4c61-a1fb-457a300349a7', '99960563-0997-41bf-8634-8672821efa38', '/seed/chair-before.jpg', 'before', now() - interval '4315266 seconds'),
  ('9f38245f-9ec3-4c67-91cb-8bb85aab999c', '99960563-0997-41bf-8634-8672821efa38', '/seed/chair-after.jpg', 'after', now() - interval '4271700 seconds'),
  ('b6eb4cd3-c7f7-4f1c-8e6d-72a83f9ca7e5', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', '/seed/pipe-before.jpg', 'before', now() - interval '4250849 seconds'),
  ('5bdfb666-af88-428b-9711-0a3326f10d00', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', '/seed/pipe-after.jpg', 'after', now() - interval '4087653 seconds'),
  ('b535859b-aa74-483a-85fc-2901feda3b4d', 'cc0f486a-b377-44df-91ca-b1c2974067e9', '/seed/wall-before.jpg', 'before', now() - interval '4119699 seconds'),
  ('0ef47368-6c9d-48c4-891a-5a0da0c76785', 'cc0f486a-b377-44df-91ca-b1c2974067e9', '/seed/wall-after.jpg', 'after', now() - interval '3950435 seconds'),
  ('44bba73d-f58e-440a-acdd-c46c3e5fd120', '43846eb4-30d9-4eab-8174-e625717b0627', '/seed/wall-before.jpg', 'before', now() - interval '3991700 seconds'),
  ('843cfbcf-d547-43cc-8925-f58474bbff50', '43846eb4-30d9-4eab-8174-e625717b0627', '/seed/wall-after.jpg', 'after', now() - interval '3783045 seconds'),
  ('9cf462dc-c925-4c79-8754-fa4116a96a6a', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', '/seed/chair-before.jpg', 'before', now() - interval '3827592 seconds'),
  ('e6ca4d7c-c546-45cc-9989-0e192e74ce50', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', '/seed/chair-after.jpg', 'after', now() - interval '3682891 seconds'),
  ('cc0dc9b8-7afe-4409-84fb-55a0cd089236', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', '/seed/wall-before.jpg', 'before', now() - interval '3696805 seconds'),
  ('a5e7e66e-abcc-41c1-8b18-678fda09180d', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', '/seed/wall-after.jpg', 'after', now() - interval '3558045 seconds'),
  ('120fc111-9d30-44c7-b0eb-86bc4a3260cd', 'cb3dff46-f3dd-4d59-b346-321999565092', '/seed/light-before.jpg', 'before', now() - interval '3557214 seconds'),
  ('90e38e96-4fcd-48fb-b4ec-aafba6817bdc', 'cb3dff46-f3dd-4d59-b346-321999565092', '/seed/light-after.jpg', 'after', now() - interval '3409128 seconds'),
  ('dc50f002-dbef-4072-bc94-ec408a9ab9ea', '38202e2b-9cd8-4060-b063-1790c36eee8c', '/seed/chair-before.jpg', 'before', now() - interval '3434586 seconds'),
  ('36da6147-6282-4131-8f9e-a0ca3660a31d', '38202e2b-9cd8-4060-b063-1790c36eee8c', '/seed/chair-after.jpg', 'after', now() - interval '3347036 seconds'),
  ('c4cd0781-345a-4d1a-9bc2-060cc92ab227', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', '/seed/chair-before.jpg', 'before', now() - interval '3339610 seconds'),
  ('b847737d-8939-4d86-81ba-1cfec787005f', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', '/seed/chair-after.jpg', 'after', now() - interval '3239116 seconds'),
  ('9fccdf56-e95b-43e7-b979-cebf6b67f906', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', '/seed/computer-before.jpg', 'before', now() - interval '3228969 seconds'),
  ('d2ee9344-9b22-4ceb-bbf4-2b5ed8c9ad6a', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', '/seed/computer-after.jpg', 'after', now() - interval '3134968 seconds'),
  ('7feaab9e-13e6-4c8b-85ad-c04f0ff257ba', '5fae4862-4002-4118-9a0d-05aa67e2db09', '/seed/pipe-before.jpg', 'before', now() - interval '3080095 seconds'),
  ('793d6f62-43f5-4fa2-8224-cd81142125fe', '5fae4862-4002-4118-9a0d-05aa67e2db09', '/seed/pipe-after.jpg', 'after', now() - interval '2977948 seconds'),
  ('33a94ec3-a9d0-4d73-9f0b-4992991e9f80', '1f807261-f2df-40b2-bafd-6a5e632eebb0', '/seed/light-before.jpg', 'before', now() - interval '2960293 seconds'),
  ('c44b559d-9065-46dd-b8ac-5b8622c2f8e9', 'f6062bae-f596-43d6-bc0c-e1d199d95b1c', '/seed/light-before.jpg', 'before', now() - interval '2817986 seconds'),
  ('9fc4a4df-b36c-4add-9aee-35c2e4d9eaaa', '45c5b233-294d-48dd-9591-993521cb969d', '/seed/aircon-before.jpg', 'before', now() - interval '2711661 seconds'),
  ('5da816c2-90f7-4381-9736-24cd9c4261c8', '45c5b233-294d-48dd-9591-993521cb969d', '/seed/aircon-after.jpg', 'after', now() - interval '2596334 seconds'),
  ('822549a8-57ae-4361-9803-1c621737cd94', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', '/seed/pipe-before.jpg', 'before', now() - interval '2569836 seconds'),
  ('61dd6546-9c26-4e04-b10b-1089fd3c8768', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', '/seed/pipe-after.jpg', 'after', now() - interval '2443442 seconds'),
  ('92a28e65-9981-40bf-8481-c535bcb893a3', '0dfce590-ed62-4417-b3db-89a56de9618c', '/seed/wall-before.jpg', 'before', now() - interval '109901 seconds'),
  ('ac9b3ded-e6c8-4d8f-b1ab-7d07aa276343', '0dfce590-ed62-4417-b3db-89a56de9618c', '/seed/wall-after.jpg', 'after', now() - interval '21366 seconds'),
  ('9e63626f-bee3-4feb-b98f-6e04f4eee9d7', 'e433cfda-040b-4362-9a59-82b703a07a3f', '/seed/wall-before.jpg', 'before', now() - interval '90960 seconds'),
  ('7cdd0675-a553-45b8-be3f-70ebc605a722', 'e433cfda-040b-4362-9a59-82b703a07a3f', '/seed/wall-after.jpg', 'after', now() - interval '14872 seconds'),
  ('e24902e8-95c7-4ea7-8b6e-45cb09b25786', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', '/seed/light-before.jpg', 'before', now() - interval '135290 seconds'),
  ('91fa4a88-48ca-49a9-acd8-428a09b5f281', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', '/seed/light-after.jpg', 'after', now() - interval '72051 seconds'),
  ('84400e0f-c70e-4577-a7a3-c32a4dc6ec75', '881c967a-13f6-4e44-ad80-2778bd006d55', '/seed/computer-before.jpg', 'before', now() - interval '2090527 seconds'),
  ('9c8033ce-aee0-4136-b01d-750842e8e569', '360616c9-07b3-4a7a-8921-bfcf7af3b736', '/seed/aircon-before.jpg', 'before', now() - interval '1929208 seconds'),
  ('8ec3fe81-c66f-490d-b1d4-4cb5ad283f25', '02ed23f7-ae00-4468-a4d3-aa66b16613f2', '/seed/computer-before.jpg', 'before', now() - interval '1844636 seconds'),
  ('b30a4cae-b442-45b3-b2df-1bad9a975346', '223996ec-e82f-4700-a592-956d7de07e7a', '/seed/aircon-before.jpg', 'before', now() - interval '1704527 seconds'),
  ('c0f9cec1-8d18-4b91-a13a-906018e2fc57', '75bf5214-dd4f-42e9-b736-dc456af3b733', '/seed/chair-before.jpg', 'before', now() - interval '1552911 seconds'),
  ('77635be0-71e4-4c34-a560-915f8b522e9f', 'ac36eace-f141-43c0-b0ff-8e63ba382d5d', '/seed/light-before.jpg', 'before', now() - interval '1399101 seconds'),
  ('8b697143-265e-4bc7-8ff9-32f5b8469fac', '42afe6af-769a-428b-955c-528fd1988f95', '/seed/aircon-before.jpg', 'before', now() - interval '1317810 seconds'),
  ('fe359c76-3f38-482f-be86-254e6a92b525', 'fa72e107-5809-4815-924a-1b5b97a70cfc', '/seed/pipe-before.jpg', 'before', now() - interval '1194984 seconds'),
  ('897397f8-5ad7-4458-8f78-74171072d245', '9d9cf0ff-2085-42b7-8dfe-c9248f15b483', '/seed/aircon-before.jpg', 'before', now() - interval '1037256 seconds'),
  ('4b82ef10-0a32-4a41-9289-715b7cc3828d', 'b89eb69d-36f9-4844-ba60-a7507023245e', '/seed/pipe-before.jpg', 'before', now() - interval '904168 seconds'),
  ('3aecb33f-b3bd-4854-ba09-406099f725b6', 'd4bbb595-ea17-4957-925a-788352263633', '/seed/pipe-before.jpg', 'before', now() - interval '815842 seconds'),
  ('388f5215-9151-4770-b009-482d06487968', '285257da-22df-4790-9ba5-549ea638c36a', '/seed/aircon-before.jpg', 'before', now() - interval '704846 seconds'),
  ('42c5469b-ab47-48e8-8c4f-be1c788e9eea', '8d68ff50-6221-4b63-8567-71b5e5fb9cfc', '/seed/light-before.jpg', 'before', now() - interval '548136 seconds'),
  ('332cdb2e-7852-4cd5-8f8a-3850f00d9bb7', '06e2842f-d84d-4ad7-b18a-e17a00fddfac', '/seed/aircon-before.jpg', 'before', now() - interval '429490 seconds'),
  ('a5f4bfec-522a-480f-aa27-c00531ecb466', '32dca21b-e58c-4537-8008-27554be35286', '/seed/wall-before.jpg', 'before', now() - interval '267964 seconds'),
  ('622286ea-d51a-437e-9a28-fa3382a0ef21', '20a5fe77-e836-4ab8-9e14-6aa9d66cade2', '/seed/wall-before.jpg', 'before', now() - interval '146515 seconds'),
  ('803df4ca-db53-4e39-bd9a-814bf8e03752', '238c135c-6766-45f2-8512-92346272a6fc', '/seed/pipe-before.jpg', 'before', now() - interval '47526 seconds'),
  ('7e8c90a5-1a21-4bb2-9878-60d23bb5f06a', 'da7f3fb0-bf70-41be-aeb2-9d093f04f397', 'https://wgpumjrmowscxckqxshi.supabase.co/storage/v1/object/public/request-images/before/2026-09-17/a3cda403-0eba-46e9-a6a9-3f713b274f3d.jpg', 'before', now() - interval '686 seconds'),
  ('d5f0271e-6bd7-43df-b31c-13b3cc2bb075', 'bf633342-773a-41de-844c-4f2d8416a799', 'https://wgpumjrmowscxckqxshi.supabase.co/storage/v1/object/public/request-images/before/2026-09-17/dbcb64fa-33d2-40d1-a23b-2f4d0580b012.jpg', 'before', now() - interval '393 seconds');

insert into status_history (id, request_id, from_status, to_status, actor_id, note, created_at) values
  ('aa622b5a-6967-44d0-9c5a-fa714ae667b5', '674c9958-5d9c-419f-9a05-9a6d451fa38f', null, 'pending', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', null, now() - interval '5096246 seconds'),
  ('4088a0b2-f669-4427-9033-8aa9d0c8bfbe', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '5074614 seconds'),
  ('ade621e3-61c7-418d-b9fc-4a2232375a69', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '5067073 seconds'),
  ('6716308b-9ce7-4b0a-b295-538d940488a9', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '5046350 seconds'),
  ('9cbee897-f670-4e63-b2a7-8d452cdf90f5', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'in_progress', 'waiting_parts', '252eeae1-34a5-4582-a2d1-bf0638d96249', 'สั่งอะไหล่จากผู้จำหน่ายแล้ว', now() - interval '5029492 seconds'),
  ('f387a52d-84db-4274-86f9-50003012ad4c', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'waiting_parts', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4829429 seconds'),
  ('18e09e15-74bb-43ea-961f-542c95a16022', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4808342 seconds'),
  ('f7219a6f-72f4-428c-9b38-2b9cfbff3d4e', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'completed', 'closed', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4700454 seconds'),
  ('4637c297-f297-488c-830d-a5f2fba6285e', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', null, 'pending', '0a85ef20-b774-47b1-b241-eee6670f3495', null, now() - interval '5003794 seconds'),
  ('ee9b9358-65c9-42f0-86ec-4395dff05529', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4990723 seconds'),
  ('a2345496-80d4-42d3-967c-46d7bd73a366', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4986268 seconds'),
  ('598508c6-1f99-4226-add2-afe274de8cf6', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4958949 seconds'),
  ('647d1341-0160-4462-8ca9-054c036f362a', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4934260 seconds'),
  ('c72db6c4-04ab-4cf6-91d8-c64e1a2dff02', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'completed', 'closed', '0a85ef20-b774-47b1-b241-eee6670f3495', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4831334 seconds'),
  ('aa4bbaa3-9f92-40d8-9d1a-c7300776c54d', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '4842647 seconds'),
  ('b121423b-e93b-469e-ac97-2ef2cdd3373a', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4821925 seconds'),
  ('ee45e97a-ae0e-4fed-931c-8779a7a95a4a', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4813765 seconds'),
  ('347216a9-1825-4b8c-99a4-89064678ca8a', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'assigned', 'in_progress', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '4805381 seconds'),
  ('3f396978-8781-409a-84a7-92786ae25490', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'in_progress', 'completed', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '4760206 seconds'),
  ('1e42be11-9299-4c8a-9687-06d47311312c', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'completed', 'closed', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4653191 seconds'),
  ('7a47780a-2231-4ca2-b91d-7a3516b1337a', '1460f660-3038-43cb-93bb-bc47d09121f4', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '4715597 seconds'),
  ('8919c37a-bd18-4aa8-b097-bb7b996fcfe0', '1460f660-3038-43cb-93bb-bc47d09121f4', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4712229 seconds'),
  ('fe2a3a6e-40d3-460a-a93e-1254d22bb06b', '1460f660-3038-43cb-93bb-bc47d09121f4', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4707268 seconds'),
  ('4f430ddb-83ae-47b5-a7c7-7dba7ce6fbf3', '1460f660-3038-43cb-93bb-bc47d09121f4', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '4702541 seconds'),
  ('14f033fb-de72-4f49-996c-858d976ea37a', '1460f660-3038-43cb-93bb-bc47d09121f4', 'in_progress', 'completed', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '4695774 seconds'),
  ('9c5401ec-28fe-45e7-a6dd-909573d85780', '1460f660-3038-43cb-93bb-bc47d09121f4', 'completed', 'closed', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4560092 seconds'),
  ('718f64ef-8069-4177-9240-94fff797175d', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', null, 'pending', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', null, now() - interval '4578926 seconds'),
  ('8607733a-4501-42b6-b8dd-3ae11c36741d', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4554314 seconds'),
  ('85390ffa-d275-4fc3-8609-b475ae68ded0', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4546756 seconds'),
  ('eeb47305-be2b-4b86-9c77-7af5f114e9f0', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4487820 seconds'),
  ('72f02ae3-7699-46c3-8c6c-55b52f4ffa06', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4451240 seconds'),
  ('acc0ff8a-2c92-4d9f-a0a6-ac7b124a6f35', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'completed', 'closed', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4371421 seconds'),
  ('08802b6b-042f-4193-b814-6b57acda2528', '5c7e3322-a7ae-4241-af38-4902ea4ee267', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '4490931 seconds'),
  ('d8a3ef57-6270-40c9-a240-04113616f411', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4478110 seconds'),
  ('44c4c60a-7d40-4a85-a409-330e82e9c571', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4468161 seconds'),
  ('f6aa9554-dfb3-4078-a56b-37d430938922', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4420012 seconds'),
  ('1bad7d32-f6a7-44c0-b29a-e5dbbb2be9c9', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4324811 seconds'),
  ('42637a2f-3d70-42c9-812b-8c40651b1aa3', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'completed', 'closed', '0a799853-dae1-4d68-a895-053babb791a8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4235164 seconds'),
  ('cba77438-c8b1-4279-98f8-420f96c02823', '99960563-0997-41bf-8634-8672821efa38', null, 'pending', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', null, now() - interval '4315266 seconds'),
  ('95d59c4a-3e4a-4534-ae1f-7d6d5a21c0c2', '99960563-0997-41bf-8634-8672821efa38', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4313269 seconds'),
  ('c184324c-8540-4adf-9203-1a669f66a8db', '99960563-0997-41bf-8634-8672821efa38', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4308886 seconds'),
  ('3824d22b-5a2f-4a2a-bd9e-c38af843ddfb', '99960563-0997-41bf-8634-8672821efa38', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4292337 seconds'),
  ('1ebaad57-951a-44b2-8a5b-8004e7556bf3', '99960563-0997-41bf-8634-8672821efa38', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4271700 seconds'),
  ('f09bbae2-c4b8-420a-be7c-30543b370c9e', '99960563-0997-41bf-8634-8672821efa38', 'completed', 'closed', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4147419 seconds'),
  ('fc0e5e2f-8778-4b38-b066-99aab27738a8', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '4250849 seconds'),
  ('9f57a6d9-2bc3-4fa7-8d9c-68a51404f593', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4232756 seconds'),
  ('88e9d740-ba12-4cbc-9ca1-09f320cf7bf3', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4219616 seconds'),
  ('949d54d9-0986-4316-aa1e-98053d99c96f', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4174828 seconds'),
  ('431bed49-2b83-4e42-9020-d3afd8334041', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4087653 seconds'),
  ('3e20193d-eb25-44d2-8590-11459a8498d1', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'completed', 'closed', '0a799853-dae1-4d68-a895-053babb791a8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '4083213 seconds'),
  ('ba47554b-10eb-4afb-ae30-d7b0714e3240', 'cc0f486a-b377-44df-91ca-b1c2974067e9', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '4119699 seconds'),
  ('21dcf0fb-b17d-4c63-a786-331057beb28e', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4113398 seconds'),
  ('261ea482-2422-44b9-949c-5ee739974829', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '4108977 seconds'),
  ('c0f02cbe-3e86-4375-bfd7-a52605ea6907', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '4055464 seconds'),
  ('0d391016-4786-426f-8bf0-ab86010df207', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3950435 seconds'),
  ('1de22d9b-239e-4c45-86b5-6eb2b09529c8', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'completed', 'closed', '0a799853-dae1-4d68-a895-053babb791a8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3904787 seconds'),
  ('84bb39f4-4983-456d-8b3f-0e2cd7f50cd2', '43846eb4-30d9-4eab-8174-e625717b0627', null, 'pending', '0a85ef20-b774-47b1-b241-eee6670f3495', null, now() - interval '3991700 seconds'),
  ('6e0b882d-6598-4568-91b7-3b2984693d99', '43846eb4-30d9-4eab-8174-e625717b0627', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3988237 seconds'),
  ('3599910e-e1f4-44fb-926c-e53bca4cb2e0', '43846eb4-30d9-4eab-8174-e625717b0627', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3974178 seconds'),
  ('a3c2763f-dd5f-4fbf-91cf-3a473469d13d', '43846eb4-30d9-4eab-8174-e625717b0627', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3969253 seconds'),
  ('b5f18145-b0d0-4bdb-b536-e9950a5440bf', '43846eb4-30d9-4eab-8174-e625717b0627', 'in_progress', 'waiting_parts', '252eeae1-34a5-4582-a2d1-bf0638d96249', 'สั่งอะไหล่จากผู้จำหน่ายแล้ว', now() - interval '3959518 seconds'),
  ('9bda4024-cb53-4707-8df1-154b4fc1213d', '43846eb4-30d9-4eab-8174-e625717b0627', 'waiting_parts', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3852501 seconds'),
  ('ad1d3e22-6af6-4e2f-bb7f-dd1104dcee8d', '43846eb4-30d9-4eab-8174-e625717b0627', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3783045 seconds'),
  ('22e7a36c-059c-419d-98e9-fdba898b706a', '43846eb4-30d9-4eab-8174-e625717b0627', 'completed', 'closed', '0a85ef20-b774-47b1-b241-eee6670f3495', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3723506 seconds'),
  ('ecb2c5c8-de17-45d0-988d-967d7b5c4e17', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '3827592 seconds'),
  ('94a4a94c-8efb-48cb-81fc-ad5e5281a3d1', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3803373 seconds'),
  ('c95fbcc2-1b51-43d4-8d94-7d0d9767534f', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3791630 seconds'),
  ('c063130f-31ad-4e17-8498-567e454c13f4', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3766402 seconds'),
  ('337b4e77-ef5a-4f78-a352-55e91151a00a', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3682891 seconds'),
  ('d83bae2f-9463-4dbb-b9c4-95837766d555', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'completed', 'closed', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3512297 seconds'),
  ('a1eecd46-b5f6-4740-8c2f-28e1100cfc7c', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', null, 'pending', '90919f40-45dc-40f4-91f9-50b8ceeba531', null, now() - interval '3696805 seconds'),
  ('7be7ddaa-1b4f-443b-8a87-0218fb17292e', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3680893 seconds'),
  ('2a5d58d8-e8bd-4cc9-a3ee-3b8c17809474', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3667168 seconds'),
  ('14f93b92-e566-4ad7-94f3-6dc7eea55b7a', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3604246 seconds'),
  ('4398b69d-e9c3-4d00-98b3-d7e83a635c33', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3558045 seconds'),
  ('449ddb35-9eb9-41ad-aba0-bc3b51ef95c3', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'completed', 'closed', '90919f40-45dc-40f4-91f9-50b8ceeba531', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3419133 seconds'),
  ('1adbf981-aa3d-4472-ae37-5ce20eee952d', 'cb3dff46-f3dd-4d59-b346-321999565092', null, 'pending', '0a85ef20-b774-47b1-b241-eee6670f3495', null, now() - interval '3557214 seconds'),
  ('36637c4e-16fe-4b4e-b317-36239181a434', 'cb3dff46-f3dd-4d59-b346-321999565092', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3533014 seconds'),
  ('8ca07ba9-b733-45fa-b093-bda2962204d5', 'cb3dff46-f3dd-4d59-b346-321999565092', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3524484 seconds'),
  ('3b244576-7a38-4bfb-9a04-b4568eba58f8', 'cb3dff46-f3dd-4d59-b346-321999565092', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '3500041 seconds'),
  ('b22b12bf-0e4c-4f8d-b8a4-261df3b0750e', 'cb3dff46-f3dd-4d59-b346-321999565092', 'in_progress', 'completed', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '3409128 seconds'),
  ('c00fe040-6cb6-4a64-8c14-cbfe3b8d1763', 'cb3dff46-f3dd-4d59-b346-321999565092', 'completed', 'closed', '0a85ef20-b774-47b1-b241-eee6670f3495', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3398297 seconds'),
  ('7b4f402b-cf41-4c17-a451-637e0a0d237f', '38202e2b-9cd8-4060-b063-1790c36eee8c', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '3434586 seconds'),
  ('2a0041ad-7d14-47ad-a131-25ea466bfe6c', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3425262 seconds'),
  ('5015340a-e658-4387-b1ae-009ac10e5aff', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3420561 seconds'),
  ('c7ccbaa8-fa80-4a2c-b32d-06bded28655c', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3392377 seconds'),
  ('3ef39984-ca88-4039-bdce-cc07ca259865', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3347036 seconds'),
  ('ecb12bb8-f21c-47d0-b70e-8aada9883fb3', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'completed', 'closed', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3318324 seconds'),
  ('905caf13-37b6-4818-9247-c021e904176a', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '3339610 seconds'),
  ('bd52dec9-55ad-4a98-92ce-b5e8bef00c9c', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3337645 seconds'),
  ('d706a0e4-929c-470f-b3c7-a51a6ccde66e', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3328663 seconds'),
  ('2b7aa170-638c-4c7d-bfd3-c98d83a83a42', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3326774 seconds'),
  ('fd60b2d7-001c-4889-8b0c-c3778ec4642d', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3239116 seconds'),
  ('8eb7e82c-8702-4c6c-8cbe-c82a7fee8a4a', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'completed', 'closed', '0a799853-dae1-4d68-a895-053babb791a8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '3092399 seconds'),
  ('dbd078d8-f6a8-4e38-886b-2eb1a0a57f60', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '3228969 seconds'),
  ('68d0530c-4ede-4db6-957d-804831e9b87b', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3226257 seconds'),
  ('ce075ba4-0d78-43fa-8cf6-34545b6244ac', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3212691 seconds'),
  ('2f2069eb-f38e-45ed-bb89-6287efd804c4', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '3209780 seconds'),
  ('eb160d85-7198-4c76-a921-9ba22b86939d', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'in_progress', 'completed', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '3134968 seconds'),
  ('fb97ea8f-dc43-48e4-b300-83976cc3b2ff', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'completed', 'closed', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2925942 seconds'),
  ('2da9e995-53f0-487c-81fa-41ebae610c84', '5fae4862-4002-4118-9a0d-05aa67e2db09', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '3080095 seconds'),
  ('0b8bdb55-6294-4373-918c-25ae5617079a', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3063117 seconds'),
  ('ca10358a-cedd-47f9-829b-8a9ae8cbd6c2', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '3050529 seconds'),
  ('40c49ae9-a906-4a5f-b7ec-c3e24493ba16', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '3007808 seconds'),
  ('5b75ebd8-1b37-455a-b4a3-fb74a85c746a', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '2977948 seconds'),
  ('33024c19-2863-48cb-ab4b-979d503f72ee', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'completed', 'closed', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2876053 seconds'),
  ('556e5546-8991-4ae9-8f62-4238df2ed649', '1f807261-f2df-40b2-bafd-6a5e632eebb0', null, 'pending', '00e1f9cd-3c8b-4016-8255-64442b85ee51', null, now() - interval '2960293 seconds'),
  ('0192eb89-c819-4776-9539-3cdf63dec017', '1f807261-f2df-40b2-bafd-6a5e632eebb0', 'pending', 'cancelled', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 'แก้ไขได้เองแล้ว', now() - interval '2958286 seconds'),
  ('86ab34a0-db05-4bdc-9097-07b3432c8616', 'f6062bae-f596-43d6-bc0c-e1d199d95b1c', null, 'pending', '0a85ef20-b774-47b1-b241-eee6670f3495', null, now() - interval '2817986 seconds'),
  ('34708b44-bde4-42b9-84ef-cf2b431b139c', 'f6062bae-f596-43d6-bc0c-e1d199d95b1c', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2815922 seconds'),
  ('840ef93f-b743-4ebb-b827-76caee8ad6d8', 'f6062bae-f596-43d6-bc0c-e1d199d95b1c', 'accepted', 'rejected', '9cfbf32c-ee8e-42c9-a961-00ca40921462', 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', now() - interval '2809881 seconds'),
  ('1a368565-672e-4595-99de-b2bbd4a57251', '45c5b233-294d-48dd-9591-993521cb969d', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '2711661 seconds'),
  ('c4039727-b7e6-4dfa-a692-d27d47d115de', '45c5b233-294d-48dd-9591-993521cb969d', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2694975 seconds'),
  ('a59f0973-d84d-4e39-bda3-9c23cd6c6a9a', '45c5b233-294d-48dd-9591-993521cb969d', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2686742 seconds'),
  ('d95ba11e-57b1-42c3-8f53-7b68df9313d5', '45c5b233-294d-48dd-9591-993521cb969d', 'assigned', 'in_progress', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '2660888 seconds'),
  ('6096fde2-65f6-49f4-b3c0-31b74f6cdda5', '45c5b233-294d-48dd-9591-993521cb969d', 'in_progress', 'completed', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '2596334 seconds'),
  ('0eda6a19-cd4b-49d0-830f-45f7a9153fa3', '45c5b233-294d-48dd-9591-993521cb969d', 'completed', 'closed', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2412973 seconds'),
  ('8e09467a-607a-484b-aa5e-57012cdae5da', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '2569836 seconds'),
  ('971193a2-b6c4-4c73-b010-97bae479c9dd', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2555884 seconds'),
  ('b963cdce-49c7-418b-b10d-31d636c974f2', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2541549 seconds'),
  ('0c2d1821-d6de-4b08-b89d-8f9a75b78a54', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '2533956 seconds'),
  ('3f4b6148-996a-4460-8ad7-64e0ed3f38de', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '2443442 seconds'),
  ('a19edff1-3b3e-4169-b043-51120456c7ed', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'completed', 'closed', '0a799853-dae1-4d68-a895-053babb791a8', 'ผู้แจ้งยืนยันว่าซ่อมเสร็จ', now() - interval '2282844 seconds'),
  ('86eb67b5-00a0-420c-985d-f2ffd7fe3493', '0dfce590-ed62-4417-b3db-89a56de9618c', null, 'pending', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', null, now() - interval '109901 seconds'),
  ('187f7eb8-e76c-4c00-a597-6bd7822188ca', '0dfce590-ed62-4417-b3db-89a56de9618c', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '107417 seconds'),
  ('3331ac3b-d988-480f-b59b-1af420f954e9', '0dfce590-ed62-4417-b3db-89a56de9618c', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '94481 seconds'),
  ('db5470ca-17f0-4cfd-adfa-9a50fa2306e2', '0dfce590-ed62-4417-b3db-89a56de9618c', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '66551 seconds'),
  ('dbbdd7a7-2062-41e3-a7d0-a32f4f198e1e', '0dfce590-ed62-4417-b3db-89a56de9618c', 'in_progress', 'completed', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '21366 seconds'),
  ('4af04ec8-8c9b-4cda-b218-8959364fdfb8', 'e433cfda-040b-4362-9a59-82b703a07a3f', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '90960 seconds'),
  ('087ac12a-eee4-44b2-938b-d4f1dd97317a', 'e433cfda-040b-4362-9a59-82b703a07a3f', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '71623 seconds'),
  ('da2d0587-2981-4ca9-9fad-4d84cc40860a', 'e433cfda-040b-4362-9a59-82b703a07a3f', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '68667 seconds'),
  ('173711c5-c976-41b9-a130-e5c8b0eb5ddb', 'e433cfda-040b-4362-9a59-82b703a07a3f', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '49491 seconds'),
  ('83c1ee3e-4f75-404a-bc05-994cdb926a6f', 'e433cfda-040b-4362-9a59-82b703a07a3f', 'in_progress', 'completed', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '14872 seconds'),
  ('16d97fcd-9142-4008-b33e-d3cf2d8f9ee2', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', null, 'pending', '90919f40-45dc-40f4-91f9-50b8ceeba531', null, now() - interval '135290 seconds'),
  ('969282ee-ef2e-4574-9826-a5d4663c9886', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '123771 seconds'),
  ('da77d163-f685-4b52-90c8-fbd5ff184d39', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '117950 seconds'),
  ('056a3b13-f1d5-4d61-b2dc-38c6dc878329', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '115361 seconds'),
  ('609b6cc7-c101-4b2d-bc6d-8fb2661afbfe', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'in_progress', 'completed', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '72051 seconds'),
  ('b82e9b72-e742-40e5-886d-0136fa5d3ba6', '881c967a-13f6-4e44-ad80-2778bd006d55', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '2090527 seconds'),
  ('da27fd0d-a69a-4069-b2d4-861268c8881b', '881c967a-13f6-4e44-ad80-2778bd006d55', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2078297 seconds'),
  ('5fe6970e-a8ab-48df-9a78-4ac9eb4b7d48', '881c967a-13f6-4e44-ad80-2778bd006d55', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '2076870 seconds'),
  ('029f5f8f-e137-4abe-a4e1-5ecbfd6fce00', '881c967a-13f6-4e44-ad80-2778bd006d55', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '2071551 seconds'),
  ('dcb898be-6010-47b0-82d1-074b14890cc7', '881c967a-13f6-4e44-ad80-2778bd006d55', 'in_progress', 'waiting_parts', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', 'รออะไหล่จากผู้จำหน่าย 2-3 วัน', now() - interval '2053837 seconds'),
  ('eefb4972-82d6-46dd-a739-2b54de4f8a0d', '360616c9-07b3-4a7a-8921-bfcf7af3b736', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '1929208 seconds'),
  ('cb51c598-899e-4bd8-88fd-19fc62728fa4', '360616c9-07b3-4a7a-8921-bfcf7af3b736', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1927050 seconds'),
  ('0c985c36-1f14-47e2-9341-511d01178d2a', '360616c9-07b3-4a7a-8921-bfcf7af3b736', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1915339 seconds'),
  ('e0107972-c6a9-4904-be35-885976f2d5e0', '360616c9-07b3-4a7a-8921-bfcf7af3b736', 'assigned', 'in_progress', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '1906274 seconds'),
  ('7cd26108-f0c0-46fd-b9d2-7d0545961637', '360616c9-07b3-4a7a-8921-bfcf7af3b736', 'in_progress', 'waiting_parts', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', 'รออะไหล่จากผู้จำหน่าย 2-3 วัน', now() - interval '1880669 seconds'),
  ('2e6ee155-f828-4efa-a2b7-227d18ed3d1f', '02ed23f7-ae00-4468-a4d3-aa66b16613f2', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '1844636 seconds'),
  ('0ecf638f-ec9f-4b08-b3ac-559c00601887', '02ed23f7-ae00-4468-a4d3-aa66b16613f2', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1821058 seconds'),
  ('b5304ce6-141f-42cd-a496-754c11ab0874', '02ed23f7-ae00-4468-a4d3-aa66b16613f2', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1816261 seconds'),
  ('7569e0d2-6ade-4c9f-9fb4-541541f621d6', '02ed23f7-ae00-4468-a4d3-aa66b16613f2', 'assigned', 'in_progress', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', null, now() - interval '1796248 seconds'),
  ('eaa8ed0f-5127-4886-9abb-1016a27d0913', '223996ec-e82f-4700-a592-956d7de07e7a', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '1704527 seconds'),
  ('907f4098-65fe-4562-9f2e-67769d797c00', '223996ec-e82f-4700-a592-956d7de07e7a', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1685777 seconds'),
  ('4615083a-1902-4dbb-a108-a09cee781468', '223996ec-e82f-4700-a592-956d7de07e7a', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1673359 seconds'),
  ('7571fb24-bc4f-45cd-b950-c6af62f47e46', '223996ec-e82f-4700-a592-956d7de07e7a', 'assigned', 'in_progress', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', null, now() - interval '1604617 seconds'),
  ('6ce7d3fa-5743-4063-b63e-b4d7e1a4c8bc', '75bf5214-dd4f-42e9-b736-dc456af3b733', null, 'pending', '5b3abd49-a767-4b9a-b40a-6adc9ee926db', null, now() - interval '1552911 seconds'),
  ('4fc7bef1-6b02-4bc8-8d52-8999c59744fb', '75bf5214-dd4f-42e9-b736-dc456af3b733', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1551133 seconds'),
  ('a9d035f8-652c-4e9b-b5e1-b19329551428', '75bf5214-dd4f-42e9-b736-dc456af3b733', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1545075 seconds'),
  ('91d5ac5f-75d3-48fd-9f24-df10f951b5e8', '75bf5214-dd4f-42e9-b736-dc456af3b733', 'assigned', 'in_progress', '252eeae1-34a5-4582-a2d1-bf0638d96249', null, now() - interval '1538243 seconds'),
  ('e43928e1-5f02-4b8b-872b-66e195da1f33', 'ac36eace-f141-43c0-b0ff-8e63ba382d5d', null, 'pending', '0a85ef20-b774-47b1-b241-eee6670f3495', null, now() - interval '1399101 seconds'),
  ('20ca76a9-0d78-46a3-a210-84c1b351417a', 'ac36eace-f141-43c0-b0ff-8e63ba382d5d', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1385514 seconds'),
  ('c15f1e10-7ed9-4630-bdc6-f136d4c941cf', 'ac36eace-f141-43c0-b0ff-8e63ba382d5d', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1373608 seconds'),
  ('6a524eb9-3853-4aaf-b3f0-51797c2f5222', '42afe6af-769a-428b-955c-528fd1988f95', null, 'pending', '00e1f9cd-3c8b-4016-8255-64442b85ee51', null, now() - interval '1317810 seconds'),
  ('164fbb42-560c-4ced-a3ad-731398756abc', '42afe6af-769a-428b-955c-528fd1988f95', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1290896 seconds'),
  ('9f6bb581-1923-4495-b677-ae028555b2ec', '42afe6af-769a-428b-955c-528fd1988f95', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1289927 seconds'),
  ('5b831903-70df-4d82-83e8-64a47edfef7b', 'fa72e107-5809-4815-924a-1b5b97a70cfc', null, 'pending', '00e1f9cd-3c8b-4016-8255-64442b85ee51', null, now() - interval '1194984 seconds'),
  ('b450bbf2-2a78-4202-8f46-a07cde5c652e', 'fa72e107-5809-4815-924a-1b5b97a70cfc', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1184881 seconds'),
  ('70ca544f-324b-453c-9029-ba4870f1b0b2', 'fa72e107-5809-4815-924a-1b5b97a70cfc', 'accepted', 'assigned', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1177189 seconds'),
  ('328a2b5c-50e8-4c3f-8eb9-c7d417767107', '9d9cf0ff-2085-42b7-8dfe-c9248f15b483', null, 'pending', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', null, now() - interval '1037256 seconds'),
  ('497581e2-8000-4b51-8cd2-d02b4d2f1285', '9d9cf0ff-2085-42b7-8dfe-c9248f15b483', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '1036053 seconds'),
  ('4aea97ec-d509-4514-be7a-f728ea6992ad', 'b89eb69d-36f9-4844-ba60-a7507023245e', null, 'pending', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', null, now() - interval '904168 seconds'),
  ('6d9441bd-40e5-4fbd-bb8b-99ea2cacc238', 'b89eb69d-36f9-4844-ba60-a7507023245e', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '900870 seconds'),
  ('9e47516b-16af-4a45-b8a1-4a03bba5bbec', 'd4bbb595-ea17-4957-925a-788352263633', null, 'pending', '00e1f9cd-3c8b-4016-8255-64442b85ee51', null, now() - interval '815842 seconds'),
  ('d7ba38f1-3d1f-4962-b872-f043e1ca0432', 'd4bbb595-ea17-4957-925a-788352263633', 'pending', 'need_info', '9cfbf32c-ee8e-42c9-a961-00ca40921462', 'ช่วยระบุหมายเลขเครื่องหรือแนบรูปมุมกว้างเพิ่มเติม', now() - interval '813382 seconds'),
  ('76684454-4259-41d4-a07a-e08449c03368', '285257da-22df-4790-9ba5-549ea638c36a', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '704846 seconds'),
  ('6732a5a0-8451-4b91-9757-8cf29e9d6c45', '285257da-22df-4790-9ba5-549ea638c36a', 'pending', 'cancelled', '0a799853-dae1-4d68-a895-053babb791a8', 'แก้ไขได้เองแล้ว', now() - interval '701151 seconds'),
  ('cfddb683-4c13-4aad-aaa1-f3cbf111a973', '8d68ff50-6221-4b63-8567-71b5e5fb9cfc', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '548136 seconds'),
  ('b55ac2d3-42b7-46a8-88ad-fd582320842d', '8d68ff50-6221-4b63-8567-71b5e5fb9cfc', 'pending', 'accepted', '9cfbf32c-ee8e-42c9-a961-00ca40921462', null, now() - interval '540762 seconds'),
  ('21d4f2da-08d0-4eda-bc50-2140d51a96ed', '8d68ff50-6221-4b63-8567-71b5e5fb9cfc', 'accepted', 'rejected', '9cfbf32c-ee8e-42c9-a961-00ca40921462', 'อยู่นอกความรับผิดชอบของงานอาคารสถานที่ กรุณาติดต่อผู้ให้บริการหอพักเอกชนโดยตรง', now() - interval '527007 seconds'),
  ('20a22c8b-8474-4c1f-bab6-e0512033f85b', '06e2842f-d84d-4ad7-b18a-e17a00fddfac', null, 'pending', '90919f40-45dc-40f4-91f9-50b8ceeba531', null, now() - interval '429490 seconds'),
  ('dc393377-7fcf-4f75-a0d1-676bfd7b3d54', '32dca21b-e58c-4537-8008-27554be35286', null, 'pending', '0a799853-dae1-4d68-a895-053babb791a8', null, now() - interval '267964 seconds'),
  ('13e55c1b-a9f7-486e-b978-ce05978f32d1', '20a5fe77-e836-4ab8-9e14-6aa9d66cade2', null, 'pending', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', null, now() - interval '146515 seconds'),
  ('f2f3b1d4-4a24-43b9-82cd-69137ecd7ec8', '238c135c-6766-45f2-8512-92346272a6fc', null, 'pending', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', null, now() - interval '47526 seconds'),
  ('cadee46d-9924-47f9-964d-3a98f649b1b9', 'da7f3fb0-bf70-41be-aeb2-9d093f04f397', null, 'pending', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', null, now() - interval '686 seconds'),
  ('2b83640f-75b4-400f-81cd-b9c3bbf92c7c', 'bf633342-773a-41de-844c-4f2d8416a799', null, 'pending', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', null, now() - interval '393 seconds');

insert into repair_notes (id, request_id, cause, parts_used, technician_id, created_at) values
  ('f4475976-702d-467c-b301-2be97556a3aa', '674c9958-5d9c-419f-9a05-9a6d451fa38f', 'ลูกลอยชักโครกค้าง', 'ชุดลูกลอย 1 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4808342 seconds'),
  ('c9a18b01-001c-455c-b485-35d040d44be5', 'a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4934260 seconds'),
  ('5ade8faa-55d6-4ed0-8b09-dae4aeecbc81', '1fbbc562-9c8b-45fe-b91a-9422256fd67d', 'สายไฟในเต้ารับหลวม', 'เต้ารับคู่ 1 ชุด', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', now() - interval '4760206 seconds'),
  ('017a6896-8f6e-46ea-bd93-ba78a6834827', '1460f660-3038-43cb-93bb-bc47d09121f4', 'Power supply เสีย', 'Power supply 500W 1 ตัว', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', now() - interval '4695774 seconds'),
  ('d9af8cc5-593b-4b6b-bee9-c142f22030e1', 'ffb70f07-e42b-4db4-ba12-a7679dc09912', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4451240 seconds'),
  ('a3c616ab-dd1a-4b41-b12c-2668bfce8c17', '5c7e3322-a7ae-4241-af38-4902ea4ee267', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4324811 seconds'),
  ('7cc3678d-449f-4d45-9dc4-45d2943896c5', '99960563-0997-41bf-8634-8672821efa38', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4271700 seconds'),
  ('70e1d9cf-8c70-4bd8-8d4b-055601b0b777', '8248d1ff-1ff8-44e1-b0cd-e0df188580f0', 'ซีลยางในก๊อกเสื่อม', 'ซีลยาง 2 ชิ้น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '4087653 seconds'),
  ('25262241-6b6d-42e5-b357-526979afea1f', 'cc0f486a-b377-44df-91ca-b1c2974067e9', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3950435 seconds'),
  ('cae1e627-00cb-4b05-be72-e979d8252baa', '43846eb4-30d9-4eab-8174-e625717b0627', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3783045 seconds'),
  ('8303ac00-62c1-43da-ae69-48c586bc596e', '74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3682891 seconds'),
  ('6ca91cd9-e319-4146-a9a9-a59b2d5336e4', '0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3558045 seconds'),
  ('d3f13205-ccb5-4734-aecd-672dcf43415d', 'cb3dff46-f3dd-4d59-b346-321999565092', 'สายไฟในเต้ารับหลวม', 'เต้ารับคู่ 1 ชุด', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', now() - interval '3409128 seconds'),
  ('9a0a25f7-3937-4a73-a066-53c79484d737', '38202e2b-9cd8-4060-b063-1790c36eee8c', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3347036 seconds'),
  ('b2295950-5e63-4300-83aa-759b2816167a', 'b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 'น็อตยึดหลุดและโครงเหล็กงอ', 'น็อตพร้อมแหวน 8 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '3239116 seconds'),
  ('f273d124-29ce-4c8c-8099-37dc304b7171', '54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 'สาย HDMI ในรางชำรุด', 'สาย HDMI 10 ม. 1 เส้น', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', now() - interval '3134968 seconds'),
  ('d121f324-5193-46f8-a5e3-f202eb8326e2', '5fae4862-4002-4118-9a0d-05aa67e2db09', 'ซีลยางในก๊อกเสื่อม', 'ซีลยาง 2 ชิ้น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '2977948 seconds'),
  ('294f1c34-2598-4d2b-9bff-42622895c4ea', '45c5b233-294d-48dd-9591-993521cb969d', 'น้ำยาแอร์รั่วและคอยล์ร้อนสกปรก', 'น้ำยา R32 1 กก.', 'b1be67ba-6252-4385-bcab-00ffc2b5af46', now() - interval '2596334 seconds'),
  ('4b610db6-a8a4-47d5-8e1a-4b446c3f268a', '0b405259-4fdd-48c1-aec8-a5abeb38ee64', 'ลูกลอยชักโครกค้าง', 'ชุดลูกลอย 1 ชุด', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '2443442 seconds'),
  ('6d50b4f7-8cc8-4c95-9af8-f03d3b1cf836', '0dfce590-ed62-4417-b3db-89a56de9618c', 'ประสานหน่วยงานที่เกี่ยวข้องดำเนินการเรียบร้อย', null, '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', now() - interval '21366 seconds'),
  ('118ed7c1-b441-42e1-9288-1923565cb074', 'e433cfda-040b-4362-9a59-82b703a07a3f', 'รอยต่อหลังคารั่วซึม', 'ซิลิโคนกันรั่ว 2 หลอด, แผ่นฝ้า 2 แผ่น', '252eeae1-34a5-4582-a2d1-bf0638d96249', now() - interval '14872 seconds'),
  ('cef59c00-b951-4b0d-aa86-1e09062ecf73', '07d7a9e5-15f4-4cf8-bb8b-db24999791a4', 'บัลลาสต์หลอดไฟเสื่อม', 'บัลลาสต์อิเล็กทรอนิกส์ 2 ตัว, หลอด LED T8 2 หลอด', '8bb156cf-dfe6-478a-8987-6b6763cbfb6a', now() - interval '72051 seconds');

insert into info_requests (id, request_id, asked_by, question, answer, answered_at, created_at) values
  ('aa9fe17a-dcee-4bba-9965-6415fecfba5e', 'd4bbb595-ea17-4957-925a-788352263633', '9cfbf32c-ee8e-42c9-a961-00ca40921462', 'ช่วยระบุหมายเลขเครื่องหรือแนบรูปมุมกว้างเพิ่มเติม', null, null, now() - interval '813382 seconds');

insert into ratings (request_id, score, comment, created_at) values
  ('674c9958-5d9c-419f-9a05-9a6d451fa38f', 5, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '4700454 seconds'),
  ('a98f4fdd-f952-47aa-9689-2c7d75eb49f1', 3, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '4831334 seconds'),
  ('1fbbc562-9c8b-45fe-b91a-9422256fd67d', 5, null, now() - interval '4653191 seconds'),
  ('1460f660-3038-43cb-93bb-bc47d09121f4', 5, null, now() - interval '4560092 seconds'),
  ('ffb70f07-e42b-4db4-ba12-a7679dc09912', 5, null, now() - interval '4371421 seconds'),
  ('5c7e3322-a7ae-4241-af38-4902ea4ee267', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '4235164 seconds'),
  ('99960563-0997-41bf-8634-8672821efa38', 5, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '4147419 seconds'),
  ('cc0f486a-b377-44df-91ca-b1c2974067e9', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '3904787 seconds'),
  ('74d0dcdf-8062-4d3b-9a1b-c25b15bbccf4', 5, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '3512297 seconds'),
  ('0d851b59-4bfb-4a2f-b242-a115cd4e8f21', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '3419133 seconds'),
  ('cb3dff46-f3dd-4d59-b346-321999565092', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '3398297 seconds'),
  ('38202e2b-9cd8-4060-b063-1790c36eee8c', 5, null, now() - interval '3318324 seconds'),
  ('b30d3ee9-da05-4deb-a78b-a0c0ec6ebd98', 4, 'ใช้เวลานานไปนิด แต่งานดี', now() - interval '3092399 seconds'),
  ('54e34d46-e1e7-49b5-a748-49e5b0c4b2b5', 5, null, now() - interval '2925942 seconds'),
  ('5fae4862-4002-4118-9a0d-05aa67e2db09', 5, 'ขอบคุณที่ช่วยดูแลครับ', now() - interval '2876053 seconds'),
  ('45c5b233-294d-48dd-9591-993521cb969d', 5, 'ซ่อมเรียบร้อยดีค่ะ', now() - interval '2412973 seconds'),
  ('0b405259-4fdd-48c1-aec8-a5abeb38ee64', 4, 'ช่างมาเร็วมาก ขอบคุณครับ', now() - interval '2282844 seconds');

insert into notifications (id, user_id, request_id, type, title, body, read_at, created_at) values
  ('c5f5ea61-19e4-4307-a2d9-c7426fe78b3e', '0a85ef20-b774-47b1-b241-eee6670f3495', 'ac36eace-f141-43c0-b0ff-8e63ba382d5d', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0004 · อาคาร CAMT ห้อง 102', null, now() - interval '1373608 seconds'),
  ('35d91422-d339-44c6-a92d-0d2ab62d56f6', '00e1f9cd-3c8b-4016-8255-64442b85ee51', '42afe6af-769a-428b-955c-528fd1988f95', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0005 · อาคาร CAMT ห้อง 304', now() - interval '5307 seconds', now() - interval '1289927 seconds'),
  ('e53d1b13-9bf0-45b8-b60d-58974049bcee', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 'fa72e107-5809-4815-924a-1b5b97a70cfc', 'assigned', 'มอบหมายช่างแล้ว', 'คำร้อง MR-2609-0006 · อาคารเรียนรวม ห้อง 202', now() - interval '5307 seconds', now() - interval '1177189 seconds'),
  ('a9853d4f-007f-4efb-9fb4-072642a7b2b0', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', '9d9cf0ff-2085-42b7-8dfe-c9248f15b483', 'accepted', 'รับเรื่องแล้ว', 'คำร้อง MR-2609-0007 · อาคารเรียนรวม ห้อง 305', null, now() - interval '1036053 seconds'),
  ('980a752c-a3e3-40e4-b009-52f5c0a7907a', 'e7f8ceab-cf38-4559-827e-c8d8be6bb239', 'b89eb69d-36f9-4844-ba60-a7507023245e', 'accepted', 'รับเรื่องแล้ว', 'คำร้อง MR-2609-0008 · อาคารคณะวิศวกรรมศาสตร์ 30 ปี ห้อง 402', null, now() - interval '900870 seconds'),
  ('4508ad82-d47f-470a-8c5a-6c09011a3d21', '00e1f9cd-3c8b-4016-8255-64442b85ee51', 'd4bbb595-ea17-4957-925a-788352263633', 'need_info', 'ขอข้อมูลเพิ่มเติม', 'คำร้อง MR-2609-0009 · อาคารคณะพยาบาลศาสตร์ ห้อง 204', now() - interval '5306 seconds', now() - interval '813382 seconds'),
  ('c258e1fb-7400-43a9-b2dc-11d3d7352cbd', '0a799853-dae1-4d68-a895-053babb791a8', '285257da-22df-4790-9ba5-549ea638c36a', 'cancelled', 'ยกเลิก', 'คำร้อง MR-2609-0010 · อาคารเรียนรวม ห้อง 205', now() - interval '5306 seconds', now() - interval '701151 seconds'),
  ('50d8a728-9109-41ee-8851-9041079d80c2', '0a799853-dae1-4d68-a895-053babb791a8', '8d68ff50-6221-4b63-8567-71b5e5fb9cfc', 'rejected', 'ปฏิเสธ', 'คำร้อง MR-2609-0011 · อาคารคณะพยาบาลศาสตร์ ห้อง 204', now() - interval '5306 seconds', now() - interval '527007 seconds'),
  ('1afbe5a4-94ba-4ed6-8b8b-eb5903534cbb', '90919f40-45dc-40f4-91f9-50b8ceeba531', '06e2842f-d84d-4ad7-b18a-e17a00fddfac', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0012 · อาคารคณะวิศวกรรมศาสตร์ 30 ปี ห้อง 401', now() - interval '5306 seconds', now() - interval '429490 seconds'),
  ('065b14db-f7b2-4f55-88b7-397816567e79', '0a799853-dae1-4d68-a895-053babb791a8', '32dca21b-e58c-4537-8008-27554be35286', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0013 · อาคารเรียนรวม ห้อง 202', now() - interval '5306 seconds', now() - interval '267964 seconds'),
  ('c3be3827-ddc4-4ef8-bace-23c253f58f10', 'c0f61d6b-cf5f-491f-b096-abae9aaa147b', '20a5fe77-e836-4ab8-9e14-6aa9d66cade2', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0014 · อาคารคณะพยาบาลศาสตร์ ห้อง 102', null, now() - interval '146515 seconds'),
  ('ccf4217e-a706-4395-9374-eaf8043ecf6c', 'ec2c0905-6030-4f78-82b1-47bb91c66df2', '238c135c-6766-45f2-8512-92346272a6fc', 'pending', 'รอรับเรื่อง', 'คำร้อง MR-2609-0015 · หอพักนักศึกษา 5 ห้อง 102', null, now() - interval '47526 seconds'),
  ('81f47619-7c09-4297-bc4b-b5ae5ddceba7', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', 'da7f3fb0-bf70-41be-aeb2-9d093f04f397', 'submitted', 'ส่งคำร้องแล้ว', 'เราได้รับคำร้อง MR-2609-0016 แล้ว จะแจ้งให้ทราบเมื่อมีความคืบหน้า', null, now() - interval '686 seconds'),
  ('7cbfa80a-e542-41e6-af99-fc966986a252', '1646cbd3-d59f-4d86-b9fa-f24829bc0d37', 'bf633342-773a-41de-844c-4f2d8416a799', 'submitted', 'ส่งคำร้องแล้ว', 'เราได้รับคำร้อง MR-2609-0017 แล้ว จะแจ้งให้ทราบเมื่อมีความคืบหน้า', null, now() - interval '393 seconds');

select setval(pg_get_serial_sequence('"SmartCMU".categories', 'id'), (select coalesce(max(id), 1) from categories));
select setval(pg_get_serial_sequence('"SmartCMU".campuses', 'id'), (select coalesce(max(id), 1) from campuses));
select setval(pg_get_serial_sequence('"SmartCMU".buildings', 'id'), (select coalesce(max(id), 1) from buildings));
select setval(pg_get_serial_sequence('"SmartCMU".rooms', 'id'), (select coalesce(max(id), 1) from rooms));

-- Next: run db/supabase-app-role.sql to create the app's own login role for this schema.
