/**
 * Builds db/supabase-setup.sql: all migrations + the current seeded data as plain INSERTs,
 * so a Supabase project can be set up by pasting one file into the SQL Editor (no local tooling).
 * Timestamps are written relative to now(), so the demo data stays "recent" whenever it is run.
 *
 * All app tables are created in a dedicated schema (default "SmartCMU", override with SETUP_SCHEMA),
 * The app connects with its own role (see db/supabase-app-role.sql), whose search_path points at this schema.
 *
 *   npm run db:reset && npm run db:export-sql
 */
import "./env";
import fs from "node:fs";
import path from "node:path";
import postgres from "postgres";

const TABLES = [
  "users",
  "categories",
  "technician_skills",
  "campuses",
  "buildings",
  "rooms",
  "request_code_counters",
  "requests",
  "request_images",
  "request_followers",
  "status_history",
  "repair_notes",
  "info_requests",
  "ratings",
  "notifications",
];
const SCHEMA = process.env.SETUP_SCHEMA || "SmartCMU";
const quotedSchema = `"${SCHEMA.replace(/"/g, '""')}"`;
const SEARCH_PATH = `${quotedSchema}, public, extensions`;

const SERIAL_TABLES = ["categories", "campuses", "buildings", "rooms"];

async function main() {
  const sql = postgres(process.env.DATABASE_URL!, { prepare: false, max: 1, onnotice: () => {} });
  const exportedAt = Date.now();

  const lit = (v: unknown): string => {
    if (v === null || v === undefined) return "null";
    if (v instanceof Date) {
      const secs = Math.round((exportedAt - v.getTime()) / 1000);
      return secs >= 0 ? `now() - interval '${secs} seconds'` : `now() + interval '${-secs} seconds'`;
    }
    if (typeof v === "number") return String(v);
    if (typeof v === "boolean") return v ? "true" : "false";
    return `'${String(v).replace(/'/g, "''")}'`;
  };

  const out: string[] = [
    "-- Smart CMU Maintenance: one-shot Supabase setup (schema + storage bucket + demo data).",
    "-- Paste into Supabase → SQL Editor → Run. Safe to re-run: it clears existing app data first.",
    "-- Generated by scripts/export-setup-sql.ts — do not edit by hand.",
    `-- All tables are created in schema ${quotedSchema} (identifier is case-sensitive).`,
    "",
    `create schema if not exists ${quotedSchema};`,
    `set search_path to ${SEARCH_PATH};`,
    "",
  ];

  const dir = path.join(process.cwd(), "db", "migrations");
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith(".sql")).sort()) {
    out.push(`-- ===== ${file} =====`, fs.readFileSync(path.join(dir, file), "utf8").trim(), "");
  }

  out.push("-- ===== demo data =====", `truncate ${TABLES.join(", ")} restart identity cascade;`, "");

  for (const table of TABLES) {
    const rows = await sql.unsafe(`select * from ${table}`);
    if (!rows.length) continue;
    const cols = Object.keys(rows[0]);
    out.push(`insert into ${table} (${cols.join(", ")}) values`);
    out.push(rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n") + ";", "");
  }

  for (const table of SERIAL_TABLES) {
    out.push(`select setval(pg_get_serial_sequence('${quotedSchema}.${table}', 'id'), (select coalesce(max(id), 1) from ${table}));`);
  }

  out.push(
    "",
    "-- Next: run db/supabase-app-role.sql to create the app's own login role for this schema.",
  );

  const target = path.join(process.cwd(), "db", "supabase-setup.sql");
  fs.writeFileSync(target, out.join("\n") + "\n", "utf8");
  console.log(`Wrote ${target} (${(fs.statSync(target).size / 1024).toFixed(0)} KB)`);
  await sql.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
