/**
 * Writes db/locations-sync.sql: the campuses, buildings and rooms of db/locations.ts as plain SQL for the
 * Supabase SQL Editor, for when the sync script cannot reach the database directly.
 *
 * The SQL only renames legacy buildings, adds what is missing and fixes room floors. It never deletes,
 * so existing requests keep their rooms. Safe to run more than once.
 *
 *   npx tsx scripts/export-locations-sql.ts
 */
import fs from "node:fs";
import path from "node:path";
import { facultyOf, LEGACY_BUILDINGS, LEGACY_ROOMS, LOCATIONS, roomFloor, roomName } from "../db/locations";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = [
  "-- Generated by scripts/export-locations-sql.ts from db/locations.ts. Do not edit by hand.",
  "-- Supabase → SQL Editor → paste → Run. Safe to run more than once; nothing is deleted.",
  'set search_path to "SmartCMU";',
  "begin;",
  "",
  "-- 0. Faculty of each building (reporters pick campus → faculty → building).",
  "alter table buildings add column if not exists faculty_th text;",
  "",
  "-- 1. Rename earlier buildings (only when the new name is not taken yet).",
];

for (const [oldName, newName] of Object.entries(LEGACY_BUILDINGS)) {
  out.push(`update buildings set name_th = ${q(newName)} where name_th = ${q(oldName)} and not exists (select 1 from buildings where name_th = ${q(newName)});`);
}

out.push("", "-- 2. Campuses and buildings.");
for (const c of LOCATIONS) {
  out.push(`insert into campuses (name_th) select ${q(c.name)} where not exists (select 1 from campuses where name_th = ${q(c.name)});`);
  for (const b of c.buildings) {
    out.push(
      `insert into buildings (campus_id, name_th) select id, ${q(b.name)} from campuses where name_th = ${q(c.name)} and not exists (select 1 from buildings where name_th = ${q(b.name)});`,
      `update buildings set faculty_th = ${q(facultyOf(b.name))} where name_th = ${q(b.name)} and faculty_th is distinct from ${q(facultyOf(b.name))};`,
    );
  }
}

out.push("", "-- 3. Rename earlier rooms in place, so their requests keep them.");
for (const r of LEGACY_ROOMS) {
  out.push(
    `update rooms set name_th = ${q(r.to)} where name_th = ${q(r.from)} and building_id = (select id from buildings where name_th = ${q(r.building)} order by id limit 1) and not exists (select 1 from rooms x where x.building_id = rooms.building_id and x.name_th = ${q(r.to)});`,
  );
}

out.push("", "-- 4. Rooms: add missing ones, fix floors of existing ones.");
for (const c of LOCATIONS) {
  for (const b of c.buildings) {
    const values = b.rooms.map((r) => `(${q(roomName(r))}, ${roomFloor(r)})`).join(", ");
    out.push(
      `with v(name_th, floor) as (values ${values}), bld as (select id from buildings where name_th = ${q(b.name)} order by id limit 1)`,
      `, upd as (update rooms r set floor = v.floor from v, bld where r.building_id = bld.id and r.name_th = v.name_th and r.floor <> v.floor returning r.id)`,
      `insert into rooms (building_id, floor, name_th) select bld.id, v.floor, v.name_th from v, bld where not exists (select 1 from rooms r where r.building_id = bld.id and r.name_th = v.name_th);`,
    );
  }
}

out.push("", "commit;", "", "-- Check: expect at least the counts in db/locations.ts.", "select (select count(*) from campuses) as campuses, (select count(*) from buildings) as buildings, (select count(*) from rooms) as rooms;", "");

const file = path.join(__dirname, "..", "db", "locations-sync.sql");
fs.writeFileSync(file, out.join("\n"));
const buildings = LOCATIONS.reduce((n, c) => n + c.buildings.length, 0);
const rooms = LOCATIONS.reduce((n, c) => n + c.buildings.reduce((m, b) => m + b.rooms.length, 0), 0);
console.log(`wrote ${file}: ${LOCATIONS.length} campuses, ${buildings} buildings, ${rooms} rooms`);
